documents/prod/example_prod_secret.exs, lib/teiserver_web/controllers/general/general_controller.ex, lib/teiserver_web/templates/general/general/gdpr.html.leex
Added contact email (to be created as an alias!), moderation purposes, account deletion info, children <13 section
=> Update Privacy Policy

lib/teiserver/account/lib/user_lib.ex, lib/teiserver/protocols/tachyon_v1/auth_out.ex, lib/teiserver/protocols/tachyon_v1/tachyon.ex, test/teiserver/protocols/tachyon/v1/tachyon_raw_test.exs
Fixes #31.
Adds icons to s.auth.login and s.auth.verify, Teifion added country.
=> Fix for missing user data in s.auth.login response

lib/teiserver/protocols/tachyon_v1/tachyon.ex, test/teiserver/protocols/tachyon/v1/tachyon_auth_test.exs
=> Added sync to clients

lib/teiserver/common/email_helper.ex
=> Fixes typo

lib/teiserver/mix_tasks/fake_data.ex
add a md5 hashed version of the password in password_hash
=> fix fake data user generation to be able to connect via spring lobbies

documents/guides/testing.md
add some doc on running the server in a debugger
=> add documentation on VSCode debugging

lib/teiserver/coordinator/coordinator_server.ex
Tested locally with skylobby client.
=> Add a temporary message for skylobby users to configure BAR CDN

lib/teiserver_web/controllers/account/profile_controller.ex, lib/teiserver_web/templates/account/profile/me.html.heex, lib/teiserver_web/templates/account/profile/tab_playtime.html.heex
Adds playtime tab on web profile.
Resolves #98
=> Added Playtime tab on web

lib/teiserver_web/templates/battle/match/ratings.html.heex
Closes #117 
- Adds a column to ratings.html for peak rating
=> Add peak rating to match ratings page

lib/teiserver_web/templates/battle/match/ratings.html.heex
=> Improve style for Ratings hint

.dockerignore, .gitignore, Dockerfile, README.md, config/container_dev.exs, config/container_prod.exs, docker-compose.dev.yaml, docker-compose.yaml, documents/guides/container_usage.md, misc/compose/config/nginx-server.conf.template, misc/compose/config/nginx.conf, scripts/build_container.sh, scripts/dev_compose.sh, scripts/gen_dev_container_secrets.sh, scripts/gen_prod_container_secrets.sh, scripts/generate_release.sh, scripts/prod_compose.sh
This PR seeks to provide new features and capabilities to the repo that primarily entail;
- Update the root Dockerfile with new functionality and capabilities that will enable those new to the repo to be able to right away have a working environment that they can build and reproduce. Even those that do not know Elixir.
- Provide a "production-ready" docker container build
- Provide a "development capable" docker container build
- Provide a docker compose that automates the deployment and setup of the entire server and all it's dependent components in order to;
- Enable reproducible production environment spinups
- Provide a fully working stack to developers, not just a working Dockerfile
- Enable portability and become agnostic of distro or OS. The only strict dependency becomes Docker.
- …
=> Add build targets to Dockerfile and add Docker Compose functionality

lib/teiserver/protocols/spring/spring_in.ex
allow tweakdefs through server side SAYBATTLE string length filter
=> allow tweakdefs through server side SAYBATTLE string length filter

lib/teiserver_web/templates/admin/chat/index.html.heex
This changes annoying old-style chat view links to the cool new style chat view links and adds a highlight for the searched player.
=> Adjust search chat link to battle/chat

lib/teiserver_web/templates/moderation/action/new_with_user.html.heex
Not the most consistent layout and set of offenses, but these are the ones that come up often-ish.
I removed the Site callbacks and a few of the less useful buttons that were obsoleted by removal of the Site login block, as I understand it.
=> Add more templates for actions

lib/teiserver_web/live/battles/lobbies/chat.html.heex, lib/teiserver_web/live/battles/lobbies/index.html.heex, lib/teiserver_web/live/battles/lobbies/show.html.heex, lib/teiserver_web/templates/admin/match/server_index.html.heex, lib/teiserver_web/templates/admin/user/full_chat.html.heex, lib/teiserver_web/templates/moderation/action/tab_reports.html.heex, lib/teiserver_web/templates/moderation/proposal/tab_reports.html.heex, lib/teiserver_web/templates/moderation/report/tab_against.html.heex, lib/teiserver_web/templates/moderation/report/tab_from.html.heex
I left these two:
lib/teiserver_web/templates/admin/lobby/lobby_chat.html.heex lib/teiserver_web/templates/admin/lobby/server_chat.html.heex
as they seemed conceptually like they could use a larger refactor first.
This should not explode. 😁
=> replace admin/chat with battle/chat in most places

lib/teiserver/protocols/spring/spring_user_out.ex
to have userID and userName at same position in server response:
=> whoIs response: syntax change

lib/teiserver/coordinator/consul_server.ex
Advise to pay attention to typos has been added
=> Edited error message when acknowledging a warning

lib/teiserver/data/cache_user.ex, test/teiserver/data/user_test.exs
Fixes https://github.com/beyond-all-reason/teiserver/issues/215
=> Don't allow registering with invalid/empty passwords

lib/teiserver_web/live/account/profile/contributor.ex, lib/teiserver_web/live/account/profile/contributor.html.heex
=> Don't allow spaces in custom flags

lib/teiserver_web/live/admin/chat/index.ex, lib/teiserver_web/live/microblog/blog/show.ex
Causes error on newer versions of Elixir
=> Remove self require

lib/teiserver/helpers/timex_helper.ex, lib/teiserver/moderation/libs/action_lib.ex
=> Use relative timestamps for moderation bot posts

lib/teiserver/account/libs/accolade_lib.ex, test/teiserver/account/account_test.exs, test/teiserver_web/controllers/logging/general_controller_test.exs
I'm taking baby steps to understand teiserver, and I figured fixing some simple tests first would be a good first step.
It seems because there's no CI lots of tests have bitrot and many seems to be failing for some trivial reasons, I'll get to others soon™
On latest master:
413 tests, 151 failures
On this branch:
414 tests, 148 failures
=> Some smol test fixing

lib/teiserver_web/controllers/admin/user_controller.ex, lib/teiserver_web/templates/admin/user/index.html.heex
What it says on the tin! See integration server `/teiserver/admin/user` for effects.
=> Improve display of new users for moderators

lib/teiserver_web/live/battles/lobbies/show.html.heex
May or may not explode, combust, detonate, or release cockroaches in the server room
=> Match Rating display on Battle page

.git-blame-ignore-revs, lib/teiserver/account/error_handler.ex, lib/teiserver_web/components/nav_components.ex
=> apply forgotten mix format

.github/ISSUE_TEMPLATE/1-bug_report.yml, .github/ISSUE_TEMPLATE/2-feature_request.yml, .github/ISSUE_TEMPLATE/config.yml
I added a Bug & Feature Request issue Form Templates.
=> Add Issue Templates

lib/teiserver/lobby/libs/lobby_restrictions.ex, test/teiserver/battle/lobby_server_test.exs, test/teiserver/lobby/libs/lobby_restrictions_test.exs
BEFORE
AFTER
```
mix test test/teiserver/battle/lobby_server_test.exs
```
```
mix test test/teiserver/battle/lobby_server_test.exs
```
Example commands to run in lobby
```
!boss me
$rename 8v8 Glitters Noobs
$setratinglevels 1 20
```
=> Better restrictions titles

lib/teiserver_web/live/battles/match/ratings.html.heex
Reverts beyond-all-reason/teiserver#370
Always opens the same match.
=> Revert "Make match open new tab on ctrl + click"

lib/teiserver_web/live/account/party/show.ex
As someone who uses parties often, I noticed this issue a while ago but haven't explored the cause.
Fixes #267
=> Fix party cancel invite and kick

test/teiserver/protocols/spring/spring_auth_test.exs, test/teiserver_web/controllers/api/spads_controller_test.exs
I was getting annoyed at seeing some compiler warning in every pull requests for unrelated stuff, so fixing them.
=> Fix some compiler warnings in tests

lib/teiserver_web/live/battles/lobbies/show.ex, lib/teiserver_web/live/battles/lobbies/show.html.heex
The balance algorithm will be displayed on lobby page and viewable if Tester permission
=> Show balance algo on lobby page for Tester

lib/teiserver/account/libs/user_lib.ex, test/teiserver/account/client_server_test.exs, test/teiserver/protocols/spring/spring_battle_host_async_test.exs, test/teiserver_web/controllers/admin/autohost_controller_test.exs
Some hacks and patches to avoid flakes
=> mark flakey tests

config/runtime.exs
The way Logger configuration works was changed in Elixir 1.15
=> Fix logger configuration

lib/teiserver/coordinator/consul_commands.ex, lib/teiserver/coordinator/consul_server.ex
Adds `$broadcast <msg>` admin  command that sends a given message to every lobby.
=> Add broadcast command

lib/teiserver/protocols/spring/spring_in.ex, test/teiserver/servers/spring_tcp_server_test.exs
=> Update SpringTcpServer state when joining channels

lib/teiserver/coordinator/consul_commands.ex, lib/teiserver/matchmaking.ex, lib/teiserver/matchmaking/pairing_room.ex, lib/teiserver/matchmaking/queue_server.ex, lib/teiserver/matchmaking/queue_supervisor.ex, lib/teiserver/player.ex, lib/teiserver/player/session.ex, lib/teiserver/player/tachyon_handler.ex, lib/teiserver/tachyon/schema.ex, priv/tachyon/schema/matchmaking/found/event.json, priv/tachyon/schema/matchmaking/ready/request.json, test/support/tachyon.ex, test/teiserver/matchmaking/matching_test.exs, test/teiserver/matchmaking/pairing_test.exs, test/teiserver/matchmaking/queue_sync_test.exs, test/teiserver/matchmaking/queue_test.exs, test/teiserver_web/tachyon/matchmaking_test.exs
This is the base logic and messaging to support matchmaking up to starting a game.
The matchmaking algorithm is merely there as a placeholder, we likely are going to change it a lot soon, but at least that gets the ball rolling.
=> Matchmaking pairing

lib/teiserver_web/controllers/tachyon.ex, test/teiserver_web/controllers/tachyon_controller_test.exs
Fixes some integration issues.
=> Subprotocol handshake

lib/teiserver/tachyon/schema.ex, test/support/tachyon.ex
The previous way would only work on a dev machine
=> Correct location of priv file location

lib/teiserver/battle/tasks/post_match_process_task.ex
There is a rare bug where if a player renames after starting the match, but before it gets processed, their win will not be recognised and the match will be considered a loss for them.
This happens because match process task was using `name` from match data when checking for wins and mapping stats. If the user renames, their current name won't match the one stored in match data. This PR uses `accountId` instead.
Example match data for reference (not directly relevant to this PR but I noticed everything but `accountId`, `name` and `win` can be missing)
```json
"players": [
{
"accountId": "1",
"allyTeam": "",
"ip": "1.2.3.4",
"loseTime": "",
"name": "Lexon",
"team": "",
"win": 1
},
{
"accountId": "2",
"allyTeam": 0,
"ip": "10.11.12.13",
"loseTime": "",
"name": "Player2",
"team": 12,
"win": …
```
=> Fix players not being correctly rated if they rename before match gets processed

lib/teiserver/coordinator/coordinator_commands.ex, lib/teiserver/matchmaking/queue_server.ex, lib/teiserver/player/session.ex, lib/teiserver/player/tachyon_handler.ex, lib/teiserver/tachyon/transport.ex, test/teiserver_web/tachyon/session_test.exs
I have a suspicion this is causing some issues spotted when integrating with the new lobby.
But it's also the correct thing to do, restarting the session as is is simply broken.
=> Less clever sessions

lib/teiserver/protocols/spring/spring_in.ex, test/teiserver/servers/spring_tcp_server_test.exs
Reverts beyond-all-reason/teiserver#479
Causes issues with hosting passworded lobbies.
=> Revert "Update SpringTcpServer state when joining channels"

lib/teiserver_web/templates/moderation/action/new_with_user.html.heex
Minor typo, just one character on one line :)
=> Update moderation template (rule A4 is now A3)

lib/teiserver_web/live/battles/match/show.ex
Fixes https://discord.com/channels/549281623154229250/1273218599653343262/1298564953107857419
=> Fix error when unprocessed match

lib/teiserver_web/live/battles/match/show.ex, lib/teiserver_web/live/battles/match/show.html.heex
`Tester`s can now see match rating status on match webpage.
=> Added match rating status

lib/teiserver/coordinator/coordinator_commands.ex
Fix https://github.com/beyond-all-reason/teiserver/issues/537
=> Update coordinator_commands.ex for discord linking instructions

lib/teiserver/player/tachyon_handler.ex, lib/teiserver/tachyon/handler.ex, priv/tachyon/schema/user/updated/event.json, test/support/tachyon.ex, test/teiserver/data/battle/lobby_chat_test.exs, test/teiserver_web/tachyon/matchmaking_test.exs, test/teiserver_web/tachyon/session_test.exs, test/teiserver_web/tachyon/user.exs
According to [the tachyon doc](https://github.com/beyond-all-reason/tachyon/blob/master/docs/schema/user.md#updated) an event should be sent upon login.
=> User updated event

lib/teiserver_web/controllers/telemetry/complex_match_event_controller.ex, lib/teiserver_web/templates/telemetry/general/index.html.heex
=> Allow Engine to view Complex Match Events

lib/teiserver_web/live/battles/match/show.ex
Make players display in rating descending (or name ascending if unranked)
=> Fix rating order

test/teiserver/coordinator/coordinator_commands_test.exs
Just some easy tests on a simple pure function.
=> add coordinator_commands_test.exs

lib/teiserver/asset.ex, lib/teiserver/asset/libs/map_lib.ex, lib/teiserver/asset/queries/map_queries.ex, lib/teiserver/asset/schemas/map.ex, lib/teiserver/autohost/registry.ex, lib/teiserver/autohost/tachyon_handler.ex, lib/teiserver/o_auth/plug/ensure_authenticated.ex, lib/teiserver/o_auth/schemas/application.ex, lib/teiserver_web/components/o_auth_application/application_form.ex, lib/teiserver_web/controllers/admin/o_auth_application_controller.ex, lib/teiserver_web/controllers/api/admin/asset_controller.ex, lib/teiserver_web/controllers/tachyon.ex, lib/teiserver_web/router.ex, lib/teiserver_web/templates/admin/o_auth_application/index.html.heex, lib/teiserver_web/templates/admin/o_auth_application/show.html.heex, lib/teiserver_web/views/api/admin/asset_view.ex, priv/repo/migrations/20250201165629_create_map_table.exs, test/support/fixtures/asset.ex, test/support/fixtures/o_auth/o_auth_fixtures.ex, test/teiserver/asset/map_test.exs, test/teiserver_web/controllers/api/admin/asset_controller_test.exs, test/teiserver_web/controllers/tachyon_controller_test.exs
This introduces the api endpoint for https://github.com/beyond-all-reason/teiserver/issues/557 
This api is restricted using oauth bearer token, and the map endpoint requires `admin.map` scope.
=> Map api endpoint

lib/teiserver/autohost/tachyon_handler.ex, lib/teiserver/lobby/libs/lobby_lib.ex, lib/teiserver/matchmaking/pairing_room.ex, lib/teiserver/player/session.ex, priv/tachyon/schema/battle/start/request.json, priv/tachyon/schema/definitions/privateBattle.json, test/teiserver_web/tachyon/matchmaking_test.exs
=> Extend battle/start message with engine, game and map

lib/teiserver/helpers/bounded_queue.ex, lib/teiserver/messaging.ex, lib/teiserver/messaging/message.ex, lib/teiserver/player/session.ex, lib/teiserver/player/tachyon_handler.ex, lib/teiserver/tachyon/transport.ex, priv/tachyon/schema/definitions/historyMarker.json, priv/tachyon/schema/definitions/unixTime.json, priv/tachyon/schema/messaging/received/event.json, priv/tachyon/schema/messaging/send/request.json, priv/tachyon/schema/messaging/send/response.json, priv/tachyon/schema/messaging/subscribeReceived/request.json, priv/tachyon/schema/messaging/subscribeReceived/response.json, test/support/fixtures/o_auth/o_auth_fixtures.ex, test/support/tachyon.ex, test/teiserver/helpers/bounded_queue_test.exs, test/teiserver_web/tachyon/messaging_test.exs
All the messaging stuff for DM. The scary +935 is a bit misleading, the addition of the json schema inflates the count quite a bit.
I believe there's going to be a special process for messaging later for lobbies and parties, but dms are simpler and can be handled this way, at least for now.
=> Messaging dm subscription

test/support/polling.ex, test/support/tachyon.ex, test/teiserver/autohost/autohost_test.exs, test/teiserver/protocols/spring/spring_auth_test.exs, test/teiserver/tachyon_battle/battle_test.exs, test/teiserver_web/controllers/tachyon_controller_test.exs, test/teiserver_web/tachyon/autohost_test.exs, test/teiserver_web/tachyon/battle_test.exs, test/teiserver_web/tachyon/session_test.exs, test/teiserver_web/tachyon/system_test.exs
Some low hanging fruits.
Maybe hold off merging that until https://github.com/beyond-all-reason/teiserver/pull/601 is merged since it changes the location of the polling helpers. Or merge and rebase the other branch, it's a small change.
=> Fix some bitrot

lib/teiserver_web/controllers/api/spads_controller.ex, test/teiserver_web/controllers/api/spads_controller_test.exs
Fixes this error: https://ptb.discord.com/channels/549281623154229250/1273218599653343262/1344087520937508914
=> Fix error on empty balance

lib/teiserver/o_auth.ex, lib/teiserver/o_auth/queries/credential_query.ex, lib/teiserver_web/controllers/o_auth/code_controller.ex, lib/teiserver_web/templates/admin/bot/show.html.heex, lib/teiserver_web/views/api/o_auth/code_view.ex, test/support/fixtures/o_auth/o_auth_fixtures.ex, test/teiserver/o_auth/credential_test.exs, test/teiserver/o_auth/token_test.exs, test/teiserver_web/controllers/o_auth/code_controller_test.exs
This should fix https://github.com/beyond-all-reason/teiserver/issues/582
=> Fix oauth error codes

lib/teiserver/account/servers/party_server.ex, lib/teiserver/protocols/spring/spring_in.ex, lib/teiserver/protocols/spring/spring_out.ex, lib/teiserver/protocols/spring/spring_party_in.ex, lib/teiserver/protocols/spring/spring_party_out.ex, lib/teiserver/tcp/spring/spring_tcp_server.ex, test/teiserver/protocols/spring/spring_party_test.exs
Not much feedback from masterbel since the first round.
I think most of the work is done and can be reviewed then merged, and any missing things or bugfixes can be done as usual.
=> Parties in chobby

lib/teiserver/protocols/spring/spring_party_in.ex, lib/teiserver/tcp/spring/spring_tcp_server.ex, lib/teiserver_web/live/account/party/index.ex, test/teiserver/protocols/spring/spring_party_test.exs
These are a bunch of fixes related to interactions between chobby and the web clients.
I was missing some subscriptions in both places which mean some interactions like invites would not propagate from web to chobby and vice versa.
=> Fix chobby/web interactions with parties

lib/teiserver/autohost/tachyon_handler.ex, lib/teiserver/player/tachyon_handler.ex, lib/teiserver/tachyon/handler.ex, lib/teiserver/tachyon/transport.ex
These are just refactoring because it was getting a bit tedious to have the `Jason.encode!` and `{:text, xxx}` everywhere.
=> Tachyon handler improvements

lib/teiserver/player/session.ex, lib/teiserver/player/tachyon_handler.ex, priv/tachyon/schema/definitions/privateUser.json, priv/tachyon/schema/user/self/event.json, test/teiserver_web/tachyon/friend_test.exs, test/teiserver_web/tachyon/user_test.exs
Some small refactoring, and changing the first event to be `user/self` + add the friends info.
=> User self event

lib/teiserver/tachyon/transport.ex
Instead of returning a server error.
=> Return invalid_request if schema validation fails

lib/teiserver/microblog/libs/poll_response_lib.ex
=> Remove unused function

lib/teiserver_web/templates/moderation/action/new_with_user.html.heex
Updated moderation templates following updated code of conduct language.
Removed automatic restrictions from the former "politics" (B1 Inappropriate topics)
Changed "main chat spam" to B6 section.
Changed KYS template to "Malicious Speech"
=> Update moderation templates

lib/teiserver/asset.ex, lib/teiserver/asset/libs/map_lib.ex, lib/teiserver/autohost/tachyon_handler.ex, lib/teiserver/matchmaking/pairing_room.ex, lib/teiserver/tachyon_battle.ex, test/teiserver_web/tachyon/matchmaking_test.exs
make use of the startbox set from the maps when creating the startscript
=> Set startboxes for matchmaking

lib/teiserver/account/schemas/user.ex, lib/teiserver/data/cache_user.ex, test/teiserver/data/user_test.exs
Adds back a case insensitive check for emails when registering and updating email.
=> Fix user email verification

lib/teiserver/battle/servers/match_monitor_server.ex
=> Added reaction to "Spring crashed !"

lib/teiserver/moderation/schemas/action.ex
Reverts beyond-all-reason/teiserver#740
=> Revert "Fix action discord_message_id type"

lib/teiserver/bridge/discord_bridge_bot.ex, lib/teiserver/communication.ex, lib/teiserver/communication/libs/discord_channel_lib.ex, lib/teiserver/data/hook_server.ex
Status updates on report update, ex: Opened, Closed, Actioned + Adds reactions reflecting the current Status
=> Added status for report messages in discord

lib/teiserver_web/components/layouts/root.html.heex, priv/static/css/brands.css, priv/static/css/regular.css, priv/static/css/solid.css
I couldnt get fontawesome icons to render when I pulled latest changes
Added the fontawesome style files for brands, regular, and solid icon types from the download package.
These files include the `@font-face` rule which loads the .woff files.
=> Fix Fontawesome not loading font files

config/config.exs, config/dev.exs, config/test.exs
override all in env specific configs instead.
=> Don't set a default Endpoint.host in config

lib/teiserver/bridge/commands/findreports_command.ex, lib/teiserver/bridge/discord_bridge_bot.ex, lib/teiserver/moderation.ex
- Findreport slash command can now search by Report ID
- Using the Mode argument, switches logic
- Exported some mutual lines into separate helper functions
=> Added findreport mode functionality

lib/teiserver/player/tachyon_handler.ex, priv/tachyon/schema/lobby/listReset/event.json, priv/tachyon/schema/lobby/listUpdated/event.json, test/teiserver_web/tachyon/lobby_test.exs
Correspond to the changes from
https://github.com/beyond-all-reason/tachyon/pull/69
=> Update lobby/listUpdated to use json patch representation

lib/teiserver_web/templates/moderation/report/tab_from.html.heex
I've changed the word Reporter to Target, as is is the Target of the report that is shown
=> Changed reporter to target, as reporter is wrong
