beyond-all-reason/teiserver

lib/teiserver/common/email_helper.ex

Missing forward slash in privacy policy link and remove HTML from plaintext
I am not experienced with elixir and was not able to test this pull request but is relatively self-explanatory.

Fix links in registration email

---

lib/teiserver/coordinator/consul_server.ex
test/teiserver/coordinator/split_test.exs

`$splitlobby` command will now only split to an empty lobby if it's engine version matches the starting lobby's engine version.
This fixes the issue where players could end in the hidden Engine testing lobby.

$splitlobby - filter different engine versions

---

config/config.exs
lib/central/general/startup.ex
mix.exs

Mac-Users are not able to get timezone information with `timedatectl list-timezones`, because of that I added a general solution for getting a list of timezones by adding the hex package [tzdata](https://hexdocs.pm/tzdata/readme.html)

Added tzdata package to get timezones

---

lib/teiserver/coordinator/consul_commands.ex
test/teiserver/coordinator/consul_commands_test.exs

From my point of view the error case, when a user is not found, is not well tested at the moment. For that, I probably need to know how to reach the expected behavior. To extend the tests. Besides that I am unsure if it is fine for the client to get an individual response for each user pulled.

Add ability to pull multible users via command into a lobby

---

lib/teiserver/coordinator/consul_commands.ex
lib/teiserver/coordinator/consul_server.ex
lib/teiserver/coordinator/coordinator_lib.ex
test/teiserver/coordinator/split_test.exs

`$splitlobby` command can now be used with a minimum number of players.
Examples:
- `$splitlobby 4` 
Will pass only if at least 4 people agreed to split to the new lobby.
- `$splitlobby` 
Works as before (sets minimum number to 1).
In addition to this, fixed a bug where the person who calls  `$splitlobby` would always be moved to a new lobby even if no one else voted to move.

Added minimum players option to $splitlobby

---

lib/central/account.ex
lib/central/account/queries/user_queries.ex
lib/teiserver/account/caches/user_cache.ex
test/central/account/accounts_test.exs

**Issue:** 
Login page at https://server4.beyondallreason.info/ is case-sensitive for email. Meaning I might be providing the correct email but in the wrong case and I get an "Invalid Credentials" error.
**Proposed Fix:**
- Added tests to expose case-sensitivity
- Added user query for case-insensitive email
- Modified several calls to use case-insensitve email query
I ran the server locally and confirmed this is solving the original bug, I can now type in my email in any cAsE and login successfully.

Fix case sensitive email field and add tests

---

assets/scss/custom/_styles.scss
lib/central_web/templates/layout/standard.html.heex

Credit is important.
Apparently my editor ate some unused indentations as well.
Have not seen any bad side effects of the body/html changes, looking through existing pages.
fixes #29

Sticky footer

---

lib/teiserver_web/controllers/moderation/report_controller.ex
lib/teiserver_web/templates/moderation/report/tab_details.html.heex

This adds a small button to the report page that tries to find the associated match's replay. Pretty much a small convenience for finding replays. I have a local Python script that actually calls bar-rts.com's API, but I wanted to keep this simple for now.
I bet the string interpolation can be done in a much cleaner way, but I had trouble nesting the curly brackets without, I think, Phoenix complaining about it, so this is my initial proof of concept version.
I also tried adding a line such as `"&maps=" <> @report.match.map`, but then I got the following:
<details>
<summary>Traceback</summary>
Exception:
** (KeyError) key :map not found in: #Ecto.Association.NotLoaded&lt;association :match is not loaded&gt;
(central 0.1.0) lib/teiserver_web/templates/moderation/report/tab_details.html.heex …

Add bar live services button to report page

---

lib/teiserver_web/controllers/battle/match_controller.ex
lib/teiserver_web/templates/battle/match/ratings_graph.html.heex

This PR does the following:
1. Closes #127 - the minimum and maximum range of the y axis is now calculated based on the extent of the skill, plus a buffer range
2. Change the mid value to be the users _skill_ not their rating value. Previously, we were showing the confidence interval to be +- the rating value even though the rating value is actual skill - certainty. The mid point now reflects the skill value and the rating_value is the line at the bottom of the graph.
3. Changes the color of the ratings values and confidence intervals to more indicative of their purpose
Updated graph:
Another example with an extreme ratings jump to the 60s: 
The progression graph DOES NOT indicate the difference between _skill_ and _rating value_ even though they indicate both of them. I'm not sure if …

Fix Clyret bug (Visual bug on progress for high TS players), fix how rating values are shown, and improve progression styling

---

lib/teiserver_web/templates/battle/match/ratings.html.heex

This does a few things:
- adds Skill Rating and Uncertainty directly. People were already solving sets of equation to get at it, let's not force them to.
- Ties the color associated with the row to the difference in skill rating after the match (green on a win, red on a loss). This was previously done from delta(Balance Rating). Since that's capped at 0, the diffs would show 0 on wins, for example, [in this case](https://discord.com/channels/549281623154229250/1115432854919327745/1116833556417757274).
- Adds notes on how Balance and Leaderboard ratings are calculated and displayed
- Clarifies which rating is being taken for the peak/change summary calculations (it's balance).
- While for many, Supreme Strait may be the name of the game, I still renamed the column from "Game" to "Map name" …

More info on Ratings page

---

lib/teiserver_web/controllers/api/spads_controller.ex

TeamFFA games are currently using FFA rating for balance, with the TeamFFA rating itself never being actually used (even though it does get updated on win/loss).
A specific handling for FFA ratings was initially added in 569d74b644b777f1768e9b3dd71c5d78f03874d1 due to both FFA and TeamFFA ratings being bugged. At this time, TeamFFA rating was based off Team rating, and it was changed to the current state of being based off FFA in bbe2fc758395bfe193b3d851fe6a3d7343611fb2 when FFA rating got fixed.
This commit reverts to using Team rating for balancing TeamFFA games.
The TeamFFA rating itself still cannot be used right now because there are still bugs as explained by Teifion, and also because the very low volume of TeamFFA games would not allow proper balance to occur in a timely manner …

balance: use Team rating for TeamFFA games

---

lib/teiserver_web/templates/battle/match/ratings.html.heex

As described - will be good to unify the terminology

Rename headers in matches/ratings web page to match website guide

---

lib/teiserver/coordinator/consul_commands.ex
lib/teiserver/coordinator/consul_server.ex
lib/teiserver/coordinator/coordinator_lib.ex
test/teiserver/coordinator/split_test.exs

Fixes #141 
Increases split time from 30 to 60 seconds.

Fix splitlobby to ignore passworded lobbies. Increase splitlobby time to 60 seconds

---

lib/teiserver/tcp/spring/spring_tcp_server.ex

- send UPDATEBATTLEINFO to all server users, added condition: changed_spectator_count
- avoid duplicate sending of UPDATEBATTLEINFO to battle users

Update battle_status on spectatorCount changes

---

lib/teiserver/bridge/message_commands.ex
lib/teiserver/coordinator/coordinator_commands.ex

remove a path for teiserver, as the production API throws Not Found.
and after investigation the path element teiserver is not needed.

Fix profile_link leading to NotFound error

---

lib/teiserver/coordinator/rikerss_memes.ex

Most, if not all, widgets affected by Anonymous Mode check if it isn't set to "disabled" rather than checking if its a valid option.

Anonymous Mode Meme Commands fix

---

changelog.md
lib/teiserver_web/controllers/api/public_controller.ex

Resolves #201.
User with country:
```
{
"name": "AccoladesBot",
"icon": "fa-solid fa-regular fa-award",
"colour": "#0066AA",
"rating": 0,
"country": "GB",
"age": 7
}
```
User without country:
```
{
"name": "SpryCherryTick",
"icon": "fa-solid lemon",
"colour": "#FF7777",
"rating": 0,
"country": "??",
"age": 8
}
```

Added country to leaderboard public API response

---

lib/teiserver_web/templates/moderation/report/index.html.heex

Fixes #211 with the edit that it will now point to `profile/<userid>` instead of the suggested `teiserver/admin/<userid>`.
The reason for this is that, while Overwatch members can view the list of reports, they cannot access the admin user view which causes an error. For moderators and those with access the overview page already has a button that leads to the admin user view ( `teiserver/admin/<userid>`).

Fix report target button

---

lib/teiserver_web/controllers/api/public_controller.ex
lib/teiserver_web/controllers/battle/ratings_controller.ex

This will let leaderboards include up to 100 players instead of the previous 30. The top 30 leaderboards are remnants of a time when we literally didn't have 100 active players to fill a top 100 leaderboard. They could be expanded to top 100 now that our playerbase has grown 20-fold.
I have tested this PR in my local dev-environment where it functioned as expected.
Solves https://github.com/beyond-all-reason/teiserver/issues/203.

Extend leaderboards from 30 to 100

---

documents/guides/local_setup.md

At some point this broke because `get_user_by_email/1` is now returning a map (cached user) instead of the user ecto struct. Let's just use the general functions provided by Ecto to fetch the root user.

Fix local setup documentation for root user

---

lib/teiserver/coordinator/consul_server.ex

Should fix #229. Tests are failing with or without the change so couldn't test.

Fix splitlobby error when original splitter leaves lobby

---

lib/teiserver/libs/test_lib.ex
test/support/server_case.ex
test/teiserver/protocols/spring/spring_auth_async_test.exs
test/teiserver/protocols/spring/spring_auth_test.exs
test/teiserver/protocols/spring/spring_battle_host_async_test.exs

With these changes, the command `mix test test/teiserver/protocols/spring/spring_auth_async_test.exs` now pass.
There are two important things:
* The `ConCache` is persisted across test. Some caches seems to be important to the application and the tests use that, so don't wipe everything blindly. More explanations in the commit itself (f4dd22fc5240d1cab7ad1ff8f22f0ddca304796a).
* As explained in 5668624ee537cd92d41b92c7f4a0b7b12228916b the `on_exit` is done in a separate process, and that messes up the "shareness" of the db pool.

Fix spring auth async tests

---

lib/teiserver/moderation/libs/action_lib.ex

`Lexon` has been moderated.
Reason: CoC E10 - Being too op, Restrictions: Permanently banned, Login
Until: `10 April 2373 02:00 `
`Lexon` has been moderated.
**Reason:** CoC E10 - Being too op
**Restrictions:** Permanently banned, Login
**Until:** `10 April 2373 02:00 `

Moderation log formatting

---

assets/scss/mdb/_card.scss

A tiny fix, where I cannot scroll left-right.

Can scroll big tables on narrow screens

---

lib/teiserver_web/live/account/profile/profile_components.ex
lib/teiserver_web/live/account/relationship/index.html.heex

Users expect chevron ranks to start at 1, but internally they start at 0. This PR just updates the number displayed on the page to be one more than the internally tracked value so users don't get confused.
closes #254 
Before
After

Show intuitive chevron rank number

---

lib/teiserver_web/live/battles/match/ratings.html.heex

This PR adds in the `uncertainty` and `uncertainty_change` values to the match rating table so that players can know what their uncertainty was and how much each match impacted their uncertainty values.
I've chosen to not highlight the change values red/green because uncertainty changes aren't inherently good/bad, and the value should only really go down over time.
relates to #255 (and might close it if this is deemed sufficient to resolve the confusion)

Display uncertainy values for each match

---

lib/teiserver/admin/libs/tool_lib.ex
lib/teiserver_web/templates/admin/general/index.html.heex

closes #241 
relating to #242, I also updated the font awesome icon for this to be a freely available one to reduce reliance on the premium version of font awesome
Before (on my local teiserver master branch, I'm not an an actual admin so I don't have access to this page in prod):
After:

Fix incorrect text for admin tools button

---

.github/workflows/elixir.yml

Adds a Github action that runs Teiserver tests.
Many tests are failing at the moment and as a result it is expected that this action will currently fail as well, however, it is still useful for future use and for checking the effect of new commits on tests without having to run them locally each time.

Add Github Actions for Elixir tests

---

lib/teiserver/account/libs/accolade_lib.ex
lib/teiserver/data/matchmaking.ex
lib/teiserver/game/libs/lobby_policy_lib.ex
lib/teiserver/mix_tasks/fake_data.ex
lib/teiserver_web/live/queues/index.ex
mix.exs

The original Parallel has not been updated since 2015 and is causing an error during compilation on newer Elixir versions.
This PR replaces Parallel with ParallelStream, a newer version with same functionality that compiles without errors on newer Elixir versions.
I recommend running 
`mix deps.clean --unused` or `mix deps.clean parallel`
`mix deps.get`
`mix deps.compile`
after merge or for testing

Replace Parallel with ParallelStream

---

lib/teiserver/game/libs/match_rating_lib.ex
lib/teiserver/libs/teiserver_configs.ex

Fixes #214.
Relevant discussion in
https://discord.com/channels/549281623154229250/855772061095559179/1210540660604538951
Basically, some 1v1 games do legitimately conclude before 3:00, notably 2:33 is a reported today timing to shut down a comm drop. Also tick/rover rushes. This keeps coming up on the discord. 90s should be pretty optimal. And if it isn't, well, it's now configurable so we can just change the duration :)
Tested to not blow up the site, not tested in-game yet.

Make minimal game duration to treat game as ranked configurable, lower default 180 -> 90

---

lib/teiserver/mix_tasks/fake_data.ex
lib/teiserver_web/live/queues/index.ex

Fake data could not be loaded since accounts did not generated into a list.

FixChange fake data accounts to generate a list. 

---

priv/repo/migrations/20240513165706_add_fk_battle_matches_lobby_messages.exs

Related to the discussion on discord.
Once merged, the migration will be applied on the next server startup.
This can also be applied manually before:
```bash
mix ecto.migrations # display migrations status
mix ecto.migrate --log-migrations-sql # apply pending migrations and print the SQL used
mix ecto.rollback # rollback the last applied migration
```
The indexes are coming from `\d+ teiserver_battle_matches` and creating any index in the `Referenced by` section that don't already exist.

Add indexes for foreign key constraints

---

lib/teiserver/account/libs/role_lib.ex

Fixes #272.
Added the community roles under admin, since admin can manage the roles on the sides of the community roles. If a moderator should have ability to assign these roles, I can  change it.

Add community roles to roles managed by Admin.

---

lib/teiserver/helpers/oban_logger.ex

measure.duration should be in :native time units, so this seems correct and works on integration server.

Log Oban jobs in milliseconds

---

config/config.exs
config/dev.exs
config/prod.exs
config/runtime.exs
documents/guides/deployment.md
documents/guides/production_setup_linux.md
documents/prod_files/example-environment-file
documents/prod_files/example_prod_secret.exs
lib/teiserver/application.ex
lib/teiserver/config_helpers.ex
mix.exs

This enable or disable the discord bridge through environment variable. This way, we can have one release bundle of teiserver that can be used for staging with the integration disabled, and the same bundle in prod.
This was done following the [nostrum doc about bundling it with the app](https://hexdocs.pm/nostrum/multi_node.html#bundling-nostrum-with-our-app).
This assume https://github.com/beyond-all-reason/teiserver/pull/278 is merged first (hence the warning about only looking at the last 4 commits).
@p2004a I think that's going to be useful for your work on ansible+docker

Dynamic discord integration

---

assets/scss/custom/_styles.scss
lib/teiserver_web/live/battles/match/ratings.html.heex

Currently in production it looks like this for small screens:
This ticket gives a better layout for smaller screens by adjusting the column widths and padding. Also I changed the uncertainty delta color to grey because it will always go down and users might be confused why that column is always red (and it's not bad to go down).
Go here http://localhost:4000/battle/ratings
Test on resolutions such as 
1360 x 768
1280 x 1024
(or similar if you don't have any of these screen sizes)

Fix ratings columns on smaller screens

---

lib/teiserver_web/templates/admin/user/tab_details.html.heex

Nothing was actually being rendered because of a typo.
Now we have this bit:

Render the section to edit user stats

---

config/runtime.exs

Because of wrong list of arguments to function, it was impossible to disable email integration.

Fix lookup for email integration enablement env var

---

lib/teiserver/libs/test_lib.ex
test/support/data_case.ex
test/support/server_case.ex
test/teiserver/protocols/spring/spring_auth_test.exs

A few fixes for some old tests.
`mix test test/teiserver/protocols/spring/spring_auth_test.exs` now returns 16 tests passed out of 16 vs 7 failures out of 16 tests on master.
Although there are still some async errors regarding tests teardown, it doesn't actually fail any tests. More info in af604750fedf11730dc9f52a53db84f3f29b9f79

More fix spring auth

---

.github/workflows/elixir.yml
lib/teiserver/account/servers/client_server.ex
lib/teiserver/battle/servers/match_monitor_server.ex
lib/teiserver/benchmark/stats_client.ex
lib/teiserver/bridge/command_lib.ex
lib/teiserver/bridge/message_commands.ex
lib/teiserver/coordinator/consul_server.ex
lib/teiserver/helpers/oban_logger.ex
lib/teiserver/lobby/libs/lobby_lib.ex
lib/teiserver/protocols/spring/spring_in.ex
lib/teiserver/protocols/spring/spring_out.ex
lib/teiserver/protocols/spring/spring_system_in.ex
lib/teiserver/protocols/spring/spring_telemetry_in.ex
lib/teiserver/protocols/tachyon_lib.ex
lib/teiserver/protocols/tachyon_v1/communication_out.ex
lib/teiserver/protocols/tachyon_v1/tachyon_out.ex
lib/teiserver_web/live/battles/lobbies/chat.ex
lib/teiserver_web/live/microblog/admin/post/show.ex
lib/teiserver_web/live/microblog/admin/tag/index.ex
lib/teiserver_web/live/microblog/admin/tag/show.ex
lib/teiserver_web/live/queues/index.ex

Draft PR for now as I'm also going to tinker with the github action. This will take squashing.

Clean up the failing tests a bit

---

lib/teiserver/account/emails.ex
lib/teiserver/common/email_helper.ex
lib/teiserver/data/cache_user.ex
lib/teiserver_web/components/layouts/app.html.heex
lib/teiserver_web/components/layouts/root.html.heex
lib/teiserver_web/controllers/account/session_controller.ex
lib/teiserver_web/controllers/admin/user_controller.ex

Address https://github.com/beyond-all-reason/teiserver/issues/289
If, for whatever reason, sending the password reset email fails, then attempt to delete the reset code so that the operation can be retried.
Also fixed a template so that flashes are shown on the login page as well.
This is what the admin UI looks like:
and this is what the user facing interface looks like:

Delete reset token if email failure

---

lib/teiserver/libs/test_lib.ex
lib/teiserver_web/live/account/profile/overview.ex
lib/teiserver_web/live/account/profile/overview.html.heex
test/teiserver/lobby/commands/explain_command_test.exs
test/teiserver_web/live/account/profile/overview_test.exs

This is for https://github.com/beyond-all-reason/teiserver/issues/178.
I only tested this through tests and have been unable to test locally. When running locally, I get region errors trying to create a lobby. I've come to understand that it's because I don't have SPADS running, but I'm unable to get SPADS working locally.
Details
--
* Join button is only visible if the user is in a lobby
Screenshots
--

Add ability to join user lobby from their profile page

---

lib/teiserver/data/cache_user.ex
lib/teiserver/protocols/spring/spring_in.ex
test/teiserver/protocols/spring/spring_auth_test.exs

Fix #305  and there's even a passing test for that \o/

Deny email change if email already taken

---

lib/teiserver/common/email_helper.ex

The code to verify the email is created and stored under user.stat.verification_code, and the reset code created was just useless.
The code that removed the use of this token was introduced in 6668f473c "general cleanup", that seems to have been an oversight.
Fixes https://github.com/beyond-all-reason/teiserver/issues/310

Don't create a reset code at user creation

---

lib/teiserver/account/error_handler.ex
lib/teiserver_web/controllers/account/session_controller.ex

How to test?
* Log out of your account.
* go to http://localhost:4000/teiserver/account/parties
* get redirected to login page
* login correctly
* you should land on the `/teiserver/account/parties` page instead of the default `/`
This is convenient for now, but it's going to be important when implementing OAuth2 (for tachyon).

Redirect to previous page after logging in

---

lib/teiserver/coordinator/consul_server.ex
lib/teiserver/lobby.ex

I want to allow friends to join private lobbies without having to enter a password.
This should be easy by bypassing the password requirement when the gatekeeper of a lobby is set to friends.
General Idea:
https://github.com/beyond-all-reason/BYAR-Chobby/issues/654

Allow friends to join private battles without a password

---

lib/teiserver_web/controllers/api/spads_controller.ex

Run this
```
mix dialyzer
```
And all the errors related to spads_controller will be gone. Full list of errors are in #321 (I didn't fix the other errors)

Fix spads_controller type errors

---

lib/teiserver_web/live/account/profile/contributor.html.heex

Fix contributor tab css and icons

---

lib/teiserver/account/libs/role_lib.ex
lib/teiserver/data/cache_user.ex

Currently many tourney winners don't get given their tourney rank icon. In the past Teifion was doing manual SQL queries to give people the tourney rank. This PR allows us to do it via the UI.
1. Login as admin and edit a user. Assign them the role of "Tournament winner". Note this is different from Tournament. Tournament role is to give access to special lobbies.
2. Launch Chobby and login as the user you assigned as tournament winner. Inside a lobby, they should have the tourney winner rank icon.

Add UI to assign tourney winner

---

lib/teiserver/coordinator/coordinator_commands.ex

1. Add chevron level to `$whois X` command. The purpose of this is to help diagnose issues where teiserver and chobby have a different idea of someone's chev level
2. There's a joke that BAR is a lobby simulator. So let's add lobby hours to `$whoami` and find out for sure if this is the case
Inside a lobby run 
`$whoami`
`$whois <username>`
Probably best testing this on integration server with real users to see what is saved for lobby hours.

Minor improvements to whoami and whois commands

---

lib/teiserver/data/cache_user.ex
test/teiserver/data/user_test.exs

Adds an additional check at registration/rename time, which considers how many times each non-alphanumeric character appears in a requested username.
If any individual symbol appears three or more times, then the new username is rejected (and registration / renaming fails).
This patch is intended to restrict unpronounceable "meme names", such as:
- `___`
- `____`
- `_____`
- `[]]][[[]`
... while still allowing names such as:
- `[[CLAN]]First_Middle_Last`
These kinds of names have exceptionally poor recognizability, and if more than one player in a lobby uses these names then it becomes more difficult to 1) discuss and coordinate with them, or 2) identify misbehaving players for reporting/kickbanning.
Notably, all-symbol names with few repeats are still allowed, such as:
- `__`
- `[[]]` …

Add restriction to number of symbols allowed in a username.

---

lib/teiserver/account.ex
lib/teiserver/account/libs/role_lib.ex
lib/teiserver/data/cache_user.ex
lib/teiserver_web/live/account/profile/contributor.ex
lib/teiserver_web/live/account/profile/contributor.html.heex
lib/teiserver_web/live/battles/match/show.ex
lib/teiserver_web/live/battles/match/show.html.heex
lib/teiserver_web/live/microblog/admin/post/index.ex
lib/teiserver_web/live/microblog/admin/post/show.ex
lib/teiserver_web/live/microblog/blog/index.html.heex
lib/teiserver_web/live/microblog/microblog_components.ex
lib/teiserver_web/router.ex

1. Contributors can now toggle whether or not they want to show their contributor icon in game. The checkbox is accessible on Contributor page and saves immediately on change.
2. Contributor will now inherit permissions from Tester and Tester will no longer inherit permission from Contributor. Previously Tester would inherit permissions from Contributor, making the Tester potentially more powerful which doesn't make sense. 
3. Added a Blog helper role to coincide with this discord post: https://discord.com/channels/549281623154229250/1243869733988864042/1243869733988864042
The name could be changed to something else but it was called "Blog helper" in the discord post.
4. Posting to blog now requires "Blog helper" permission. Contributors will inherit this permission. Since Tester no …

Blog Helper + Permission improvements + Toggle contributor icon

---

lib/teiserver/helpers/styling_helpers.ex
lib/teiserver/moderation/queries/report_group_queries.ex
lib/teiserver_web/controllers/admin/match_controller.ex
lib/teiserver_web/live/account/profile/overview.ex
lib/teiserver_web/templates/admin/user/smurf_list.html.heex

Some minor changes.
Running `mix compile --all-warnings --warnings-as-errors` now passes, no more compiler warnings.

Fix compiler warnings

---

lib/teiserver/chat/chat_room_cache.ex
lib/teiserver/data/matchmaking.ex
lib/teiserver/game/libs/lobby_policy_lib.ex

Because the `:lists` cache has an expiry time of 1 minutes, if there's no activity for a given list after a minute, retrieving the list would return `nil` and that causes problem when the code expects `[]`.

Defaults cache lists to empty lists

---

lib/teiserver/data/cache_user.ex
lib/teiserver_web/controllers/admin/user_controller.ex

Currently, only the most-recently-used IP address ("last_ip") for each account is stored in the database. This 2-line PR saves the IP used when an account was registered ("first_ip") as well, accessible to Admins and Moderators.

Save first_ip at registration time.

---

lib/teiserver/coordinator/consul_commands.ex
lib/teiserver/coordinator/consul_server.ex
lib/teiserver/lobby.ex
lib/teiserver/lobby/schemas/lobby_struct.ex
lib/teiserver/lobby/servers/lobby_server.ex
test/teiserver/battle/lobby_server_test.exs

This command allows Hosts to specify a string that can be used to quickly describe a lobby's currently-configured settings.
The teaser is currently used in the title of a lobby, similar to the existing behavior but without using the "$rename" command. This gives the benefit of not potentially overriding a custom player-set lobby name.
____
This PR is a complement to https://github.com/beyond-all-reason/spads_config_bar/pull/136 , and implements the Teiserver-side command used in that PR. Since BarManager's rename functionality is currently broken, it does not particularly matter which of these two PRs is merged first (no harm will be done if BarManager is using a non-existent command).
This PR specifically **does not** update the `$rename` command, as that would impact player-set lobby …

Add "$set-config-teaser" Host-command. (Prerequisite to fixing #371)

---

lib/teiserver/coordinator/consul_commands.ex
lib/teiserver/lobby.ex
lib/teiserver/lobby/servers/lobby_server.ex

_(Otherwise, any non-updated SPADS instances will regularly set the lobby name back to the default)_
Background and summary:
With the new "!rename" command added to the BarManager SPADS plugin, a host may attempt to rename its lobby at the request of a player. Furthermore, BarManager no longer automatically changes lobby names (instead, it only updates the lobby's Teaser).
However, after the very first rename for a lobby (starting from initial creation), Teiserver currently forbids any further renames originating from the host. This PR removes that restriction, allowing "!rename" to function as expected.

Bugfix: Allow hosts to rename lobbies with equal priority to players.

---

lib/teiserver_web/controllers/api/spads_controller.ex

Read https://github.com/beyond-all-reason/teiserver/issues/338 for context.
Once https://github.com/beyond-all-reason/spads_config_bar/pull/131 is merged, SPADS will directly request the correct rating type and the Teiserver side code for determining team subtype will no longer be needed.
(Small note: `TeamFFA` renamed to `Team FFA` to match the name SPADS will request.)

spads_controller get_rating cleanup

---

lib/teiserver/coordinator/consul_commands.ex
lib/teiserver/coordinator/consul_server.ex
lib/teiserver/coordinator/coordinator_lib.ex
lib/teiserver/data/cache_user.ex
test/teiserver/coordinator/consul_commands_test.exs

`$playerlimit <number>` - sets maximum player count limit for current host only, used to change the default 16 player limit.
This PR makes `$playerlimit` command Admin only, first of its type.

$playerlimit as Admin only command

---

lib/teiserver_web/live/battles/match/ratings.html.heex

Go to matches > ratings > large team
Currently if you hold ctrl + click link, it opens in same window
This PR will make it so that if you hold ctrl + click a row it will open in new tab.
Go to matches > ratings > large team
Hold ctrl + click link, it should open in new tab
Clicking normally will open in same tab

Make match open new tab on ctrl + click

---

lib/teiserver/account/libs/relationship_lib.ex
lib/teiserver/coordinator/consul_server.ex
lib/teiserver/libs/teiserver_configs.ex

When avoid is triggered the coordinator will send a message. Avoid can be triggered based on percentage or raw amount.
Also fixes some bugs because a function should have used player ids but it was being sent player objects
Use >= instead of > for checks to make it align with description in Admin config description.
Some default configs have been changed, but still overridable by admin:
**Block triggers**
50% or 8 players (previously 66% or 8 players)
**Avoid triggers**
50% or 6 players (previously 50% or 4 players)
I think nobody will trigger these anyway. Avoid trigger increased because otherwise I think it will trigger too easily on special event lobbies.

Coordinator send message when avoid is triggered

---

lib/teiserver_web/live/battles/match/ratings.html.heex

This fixes a bug where stretched-link class took up the whole screen. We use position-relative to limit it to one row.
Go to a ratings page to view matches. Test that links open for each row and that the match id is different.

Fix stretched-link taking up whole screen on ratings page

---

lib/teiserver_web/live/battles/lobbies/chat.ex

Currently, any non-Muted user is allowed to read and send lobby chat messages via the website.
However, the use-case for this feature is not very strong for the typical player, and we occasionally see it abused by players who have been kickbanned from the lobby (to flame anyone involved in the kickban).
Therefore, this patch restricts web-based chat such that only users with either the "Admin" or "Moderator" roles are able to send messages.
____
Implements #399.
Screenshots from local testing:
- Users with `Admin`/`Moderator` roles can chat:
- Users without those roles can only read chat:
To test:
1. Log in as an `Admin`/`Moderator` user
2. Browse to <TEISERVER_HOSTNAME>/battle/lobbies and click "CHAT" for any lobby
3. Observe that the chat bar and Send button are shown
4. Repeat steps …

Make web-based lobby chat read-only for non-Admin/Moderator users.

---

documents/dev_designs/tachyon_system.md

Better to see the [rendered version](https://github.com/geekingfrog/teiserver/blob/tachyon-doc/documents/dev_designs/tachyon_system.md) on the fork's branch.
This is a high level overview of how I see the lobby/matchmaking/player/autohost interactions in tachyon.

Add design doc for tachyon basic systems

---

lib/teiserver/battle/balance/brute_force.ex
lib/teiserver/battle/balance/brute_force_types.ex
lib/teiserver/battle/libs/balance_lib.ex
lib/teiserver/helpers/combinations_helper.ex
lib/teiserver_web/live/battles/match/show.html.heex
test/teiserver/battle/balance_lib_internal_test.exs
test/teiserver/battle/brute_force_internal_test.exs
test/teiserver/battle/brute_force_test.exs

Many people want a balance algorithm that keeps parties together more often. This algorithm goes through every possible combination and picks the best combination. The original idea was from Suuwassea here: https://discord.com/channels/549281623154229250/855772061095559179/1235344149713260584
1. Team count must equal 2
2. Player count must be <= 16
3. Even number of players
If any of these conditions aren't met, the default balancer will be called instead
Each combination will be given a score as follows:
```
score = rating_diff_penalty + broken_party_penalty
```
rating_diff_penalty  is just the difference in team ratings
broken_party_penalty is the number of broken parties * broken_party_multiplier
broken_party_multiplier = 3
Pick the combination that scores the lowest.
Go to to any …

Add brute force balance algo

---

lib/teiserver/lobby/libs/lobby_restrictions.ex

Add more lobby tips that will trigger on certain lobby titles. In the future these tips can be removed if we can incorporate it as part of Chobby UI.
In a new lobby boss yourself then rename the lobby to contain noob or rotato (or both) e.g.
```
$rename Noob Rotato
```
Or 
```
$rename Noob
$rename Rotato
```

More lobby tips

---

lib/teiserver/account/libs/role_lib.ex
lib/teiserver/mix_tasks/update_user_permissions.ex

After changing role_lib, permissions in the database need to be updated. Recently Blog Helper role was added and permissions are now not correct. 
Fix #395 
```
mix teiserver.update_user_permissions
```
This will now update everyone's permissions. 
Now to check run the query below on the db. It will show you the permissions of users. Ensure contributors have "Blog Helper"
```
select id, name, permissions, roles  from account_users au 
where 'Contributor'=ANY(au.roles)
```

Script to update permissions after role_lib.ex changed

---

lib/teiserver/protocols/spring/spring_in.ex

Teiserver enforces a maximum message length for the `SAYBATTLE` and `SAYBATTLEEX` Spring messages. These messages are limited to 256 characters by default, but they are increased if the message begins with certain prefixes.
Currently, when these messages begin with `$welcome-message`, the limit is raised to 1024 characters.
This patch adds `!welcome-message` to the that special case check, so that both versions of the command have the same limit of 1024.

Use same max length for `!welcome-message` and `$welcome-message`.

---

lib/teiserver/protocols/spring/spring_in.ex
lib/teiserver/protocols/spring/spring_out.ex

see: https://github.com/beyond-all-reason/teiserver/issues/341
With this PR spads can be extended to send the originator of !ring as a second argument to RING
The second format is only allowed for bot users, so that other clients can not impersonate others.
conventional RING:
```
<-- SpadsHostUser: RING UserToRing
--> UserToRing: RING SpadsHostUser
```
2nd format with this PR:
```
<-- SpadsHostUser: RING UserToRing Originator
--> UserToRing: RING Originator
```

extends RING with a second argument for originator

---

lib/teiserver/battle/libs/balance_lib.ex
lib/teiserver_web/live/battles/match/show.ex

Currently the balancer is using 
```
rating = skill - 2* uncertainty
```
It should be using
```
rating = skill - uncertainty
```
Bug was introduced in this PR: https://github.com/beyond-all-reason/teiserver/pull/328/files#r1716189573
See https://discord.com/channels/549281623154229250/1245516077547389009/1271838783750406155
Notice the rating in chobby and the rating in $explain is different. $explain rating is less than rating in chobby by roughly sigma.
The server update was done on 1 August so this bug has been here for about two weeks.
For the balance tab on the website, I have removed the fuzz multiplier for the bottom section so we can debug this easier. Fuzz multiplier still gets applied in game though for teifion's algo.
You can test this fix by first logging in as a user (like …

Fix balance rating bug

---

lib/teiserver_web/controllers/admin/user_controller.ex

something I missed for https://github.com/beyond-all-reason/teiserver/pull/408 is that the [default user query](https://github.com/geekingfrog/teiserver/blob/348972752fe01e876adefa723c16fbff29054c49/lib/teiserver/account/queries/user_queries.ex#L18) has a limit of 50. So for people like Lexon with a ton of friends, that page would only show up to 50 users total.

Display *all* the friends (and avoid and other)

---

lib/teiserver/admin/tasks/daily_cleanup_task.ex

Only keep the daily vacuum analyze query. This one can be run concurrently with other read/write operation.
The cost is that some deleted rows would still occupy space on disk, but hopefully it won't cause logging and disconnection issue.
This is a bit of a stopgap measure until we figure out the true cause of the morning disconnections.

Remove vacuum FULL from daily cleanup task

---

lib/teiserver/coordinator/consul_commands.ex
lib/teiserver/coordinator/consul_server.ex

Currently SPADS has a command balancealgorithm. It is calling teiserver command balancemode. For consistency we should add a teiserver command called `balancealgorithm`. This PR adds balancealgorithm command that does exactly the same as balancemode but it can be called by SPADS one to one.
When you give an invalid command parameter via `!balancealgorithm blah`, the error isn't displayed in lobby. So Lobby.sayprivateex has changed to ChatLib.say
For example currently in production if I use `!balancealgorithm split_one_chevs` no error is visible (but it should show that it is not a valid balance algo).
Set yourself as boss. Then run these commands
```
$balancealgorithm split_noobs
$balancemode loser_picks
$balancealgorithm x
```

Add balancealgorithm command

---

config/config.exs
lib/teiserver/account/libs/user_lib.ex
lib/teiserver/mix_tasks/fake_data.ex
lib/teiserver/mix_tasks/gen_token.ex
lib/teiserver/o_auth.ex
lib/teiserver/o_auth/queries/code_query.ex
lib/teiserver/o_auth/queries/token_query.ex
lib/teiserver/o_auth/tasks/cleanup.ex
lib/teiserver/o_auth/tasks/gen_token.ex
test/teiserver/o_auth/code_test.exs
test/teiserver/o_auth/gen_token_test.exs
test/teiserver/o_auth/token_test.exs

Some utilities to tie up some lose ends with oauth stuff and make developing tachyon easier.
* a mix task to generate an oauth token for a given user
* extend fakedata to seed a basic oauth application
* a cleanup task to delete from DB the expired codes and tokens

Tachyon dev conveniences

---

lib/teiserver/helpers/cache_helper.ex

This makes the application more robust. If a cache process is down, it shouldn't be fatal and the function can still be run to produce the result.

Don't crash when cache is down

---

lib/teiserver/data/cache_user.ex

This PR seeks to improve the user experience when reconnecting after a client crashes.
Currently, if a session already exists for a user and a client attempts to log in as the same user, the following happens:
- The login flood protection count is incremented
- The existing session is disconnected
- The new login attempt is rejected with instructions to try later
This patch changes that last point. Now, the following happens:
- The login flood protection count is incremented
- The existing session is disconnected
- The new login attempt proceeds as usual
The login attempt may still fail, for example if Teiserver's number of active sessions is at capacity; however, for typical cases the login will succeed.
(Note: most of the usual login checks occur before any existing sessions are …

Make new login sessions replace existing sessions.

---

lib/teiserver/battle/balance/default_balance.ex
lib/teiserver/battle/balance/default_balance_types.ex
lib/teiserver/battle/balance/loser_picks.ex
lib/teiserver/battle/balance/split_noobs.ex
lib/teiserver/battle/libs/balance_lib.ex
lib/teiserver/libs/teiserver_configs.ex
lib/teiserver/lobby/commands/explain_command.ex
lib/teiserver/lobby/libs/lobby_restrictions.ex
test/teiserver/battle/balance_lib_internal_test.exs
test/teiserver/lobby/commands/explain_command_test.exs

This PR creates a new balance algo called "default" which becomes the default. It will call 
If team size != 2 then call loser_picks
Otherwise if at least one newish player call split_noobs
Otherwise call loser_picks
Finally complaints over years where people say that new players are overrated can be put to rest. I have been observing multiple noob lobby games with split_noobs and am happy with the results (other than the chev icon being wrong for an unknown reason sometimes).
In SPADS we would later need to make a change to make loser_picks not voteable, but instead make default voteable instead.
You can go to website and pick default from the balance dropdown when inspecting a match

default balance algo determine whether to pick loser_picks or split_noobs depending on circumstances

---

lib/teiserver_web/live/admin/chat/index.ex
lib/teiserver_web/router.ex

Currently, users with the "Reviewer" role are only able to view chat logs for individual/reported matches.
This change allows those users to also use the global chat search tool (`<...>/admin/chat`), so that they can search a player's chat history for patterns of behavior.
This change was approved in principle by @PtaQQ (but, he did not review the code itself).

Allow Moderation Reviewers to access the global chat search tool.

---

lib/teiserver_web/templates/moderation/action/new_with_user.html.heex

This patch makes several changes to the default templates for new moderation actions:
- Remove currently-unnecessary "kickban abuse", "leaving early", and "position leave/stop" templates.
- New templates for "passing info", "unpausing", and "politics".
- New "addon" templates for frequent/intense offenses and bot games.
- Update CoC rule reference (A4->A3) based on the most recent CoC.
- Include the original ("bad") username in the "rename" template.
- Make punctuation/capitalization consistent for all templates.
Testing note; these templates can be found at the following URL, for users with the appropriate permissions:
- https://server4.beyondallreason.info/moderation/action/new_with_user?teiserver_user=<<USER_ID_NUMBER>>

Various updates for moderation action templates.

---

lib/teiserver/application.ex
lib/teiserver/autohost/tachyon_handler.ex
lib/teiserver/data/cache_user.ex
lib/teiserver/matchmaking.ex
lib/teiserver/matchmaking/queue_registry.ex
lib/teiserver/matchmaking/queue_server.ex
lib/teiserver/matchmaking/queue_supervisor.ex
lib/teiserver/matchmaking/system.ex
lib/teiserver/player/session.ex
lib/teiserver/player/session_registry.ex
lib/teiserver/player/tachyon_handler.ex
lib/teiserver/tachyon/handler.ex
lib/teiserver/tachyon/schema.ex
lib/teiserver/tachyon/transport.ex
lib/teiserver_web/controllers/tachyon.ex
priv/tachyon/schema/matchmaking/cancel/request.json
priv/tachyon/schema/matchmaking/list/request.json
priv/tachyon/schema/matchmaking/queue/request.json
test/support/tachyon.ex
test/teiserver/matchmaking/queue_sync_test.exs
test/teiserver/matchmaking/queue_test.exs
test/teiserver_web/controllers/logging/audit_log_controller_test.exs
test/teiserver_web/controllers/logging/general_controller_test.exs
test/teiserver_web/tachyon/matchmaking_test.exs
test/teiserver_web/tachyon/session_test.exs
test/teiserver_web/tachyon/transport_test.exs

This is the first step to implement matchmaking, in a very mvp state.
With this, one can join and leave queues, although there is exactly one queue (1v1). There is nothing happening after this point, the actual grouping of players and messaging should be the next pull request.
Also a note, party will be supported since a queue member can be made of multiple players.
The queues are heavily inspired from the [the existing queues made by teifion](https://github.com/beyond-all-reason/teiserver/blob/e584d6bac272c5ef7bd7973b8676f499dcf9cad8/lib/teiserver/data/matchmaking.ex#L1-L35) but ultimately I chose a slightly different approach:
* existing queues have attributes that tie them to a UI like `colour` or `icon`. I think it's a distraction for the mvp and would rather focus on the core logic
* …

Tachyon matchmaking: join and leave queues

---

lib/teiserver/matchmaking/queue_server.ex
lib/teiserver/player.ex
lib/teiserver/player/session.ex
test/teiserver_web/tachyon/matchmaking_test.exs
test/teiserver_web/tachyon/session_test.exs

The bits I forgot:
* a player that doesn't reconnect soon enough should have its session removed.
* when the session dies, the corresponding player is removed from any joined matchmaking queues.

Tachyon timeout

---

lib/teiserver/battle/libs/balance_lib.ex
lib/teiserver/coordinator/consul_commands.ex
lib/teiserver/libs/teiserver_configs.ex
test/teiserver/battle/balance_lib_internal_test.exs

The following algos are now callable via boss
```
$balancealgorithm default
$balancealgorithm auto
$balancealgorithm split_noobs
```
default will check the config for what it should pick (loser_picks probably). 
In the future maybe could rename DefaultBalance to be AutoBalance but I wanted to keep this PR short.
For SPADS I need to adjust so that auto is an option.
auto will pick between split_noobs or loser_picks depending on circumstances
You can simply call the algos listed above.
When you call "default" the text output will say loser_picks

Naming improvements for balance algos

---

lib/teiserver/lobby.ex
lib/teiserver/lobby/libs/chat_lib.ex

This patch allows users with an active chat restriction to use several common/necessary commands. Limitations are placed on both the commands that are allowed, as well as on the parameters (if any) allowed with each command. The following are allowed:
- `!vote`, and the various yes/no/blank parameters for it
- `!endvote` and `!ev`
- `!help`
- `!balance` (or a vote for it)
- `!start` (or a vote for it)
- `!forcestart` (or a vote for it)
- `!stop` (or a vote for it)
- `!resign` (or a vote for it)
Other commands, including commands to adjust various game settings, are still restricted. This is because most other commands would require almost-arbitrary parameters to be useful, and so they would provide an avenue to bypass a chat restriction.
A few commands were not whitelisted because they …

Allow chat-restricted users to run whitelisted commands.

---

lib/teiserver/battle/balance/split_noobs.ex
test/teiserver/battle/split_noobs_internal_test.exs
test/teiserver/battle/split_noobs_test.exs

This PR increases the probability of the best captain getting paired with the worst noob. Based on feedback here: https://discord.com/channels/549281623154229250/1275366409722925056/1281547394844065812
After we brute force 14 players, there will be two more remaining players for the teams to draft.
BEFORE
Lowest team rating gets pick priority
AFTER
Lowest (team rating + captain rating) gets pick priority
Therefore having a strong captain reduces your odds of getting pick priority and you're likely to get the worst noob i.e. the one chev. Often after brute force, the team ratings will be super close like one rating diff off.
A test case has been added where we have strong captain (DUFFY who is 10 points higher than the next best) and his team should also have the worst player (the one …

Increase chance worst noob paired with best captain

---

lib/teiserver/game/servers/balancer_server.ex
lib/teiserver_web/controllers/api/spads_controller.ex

Resolves #337 
`Team FFA` is now using `Large Team` ratings for balancing (matches will still rated as `Team FFA` )
Cleaned up spads_controller balance battle response, it was getting ratings which weren't even sent to or used by SPADS.

Fix TeamFFA ratings and balance

---

lib/teiserver/protocols/spring/spring_in.ex

We had an error where data contained invalid characters causing an ArgumentError exception when trying to run regex.

Validate data in spring_in

---

lib/teiserver_web/templates/moderation/action/new_with_user.html.heex

Use a combination of "All lobbies" and "Room chat" restrictions as the default for moderately-severe offense templates.
Part of https://github.com/beyond-all-reason/teiserver/issues/459

Update default moderation action templates for 'moderate' offenses.

---

lib/teiserver/battle/balance/split_noobs.ex
test/teiserver/battle/split_noobs_internal_test.exs
test/teiserver/battle/split_noobs_test.exs

If the leader of the lobby is double the rating of the next best player, simple draft does not give a good result. In this case we should use brute force instead of a simple draft. (We still only brute force max 14 players and draft the remaining).
Sample data:
https://discord.com/channels/549281623154229250/1275366409722925056/1282647881043542047
The match linked in discord has been copied to one of the test cases. You can see the score (team difference) is zero before the weak players are drafted.

Improve split_noobs when very imbalanced captains

---

lib/teiserver_web/live/battles/lobbies/show.html.heex

Knowing uncertainties is useful for understanding how balance is working in a lobby. For auto balance, split_noobs will be used in lobbies where there is a player with high uncertainty. Make the uncertainty column viewable to tester perm. It is currently viewable by mod perm but mods don't really need to see it. Plus mods with contributor role will also have tester perm.

Make uncertainties viewable for tester on website lobby

---

lib/teiserver/coordinator/coordinator_lib.ex
lib/teiserver/coordinator/rikerss_memes.ex

A late cleanup of the rikers meme file.
The pr to move these options: https://github.com/beyond-all-reason/Beyond-All-Reason/pull/3746
Removed:
- nodefence - hardcoded list, moved to game modoption
- nodefence2 - duplciate of nodefence, but with llts disabled for past adaptabilty tournament
- greenfields - already an ingame modoption
- hardt1 - hardcoded list, swapped for a remove tech 1.5, can be recreated with disable tech1.5, tech 2 and tech 3
- noscout - hardcoded list, hard to maintain here, to be ported
- hoversonly - part of the adaptablity tournament, moved to discord other mods section
- nofusion - hardcoded list, moved to game modoption
- armonly coronly legonly armvcor - modoption required for these to be removed.

Memes: Late Cleanup

---

lib/teiserver_web/live/battles/lobbies/show.html.heex

Currently if we go here: https://server4.beyondallreason.info/battle/lobbies/show/9517
only testers can see the balance algorithm
However, it is useful for normal users to know such as if they want to play in party certain algos are better for them. It is not very intrusive as most people won't even use the website for joining games so it would only be used by advanced users.
An example is MVPete https://ptb.discord.com/channels/549281623154229250/1284942772482347159/1285110298306674729
who dodged games to get parties to work. It might be more convenient to use the website to find games where the balance algo is favourable to parties.

Reveal balance algorithm to regular users on website

---

documents/guides/local_setup.md

When attempting to install erlang via asdf, the installation notes the following warning : 
```
*********************************************************************
**********************  APPLICATIONS DISABLED  **********************
*********************************************************************
crypto         : No usable OpenSSL found
odbc           : ODBC library - link check failed
ssh            : No usable OpenSSL found
ssl            : No usable OpenSSL found
```
When the developer then runs `mix deps.get`, they receive the following error:
```
** (Mix) The application "crypto" could not be found. This may happen if your Operating System broke Erlang into multiple packages and may be fixed by installing the missing "erlang-dev" and "erlang-crypto" packages
```
Since it …

Updated local_setup documentation to recommend installing libssl-dev 

---

lib/teiserver/battle/balance/split_noobs.ex
test/teiserver/battle/split_noobs_deviation_test.exs
test/teiserver/battle/split_noobs_internal_test.exs
test/teiserver/battle/split_noobs_test.exs
test/teiserver_web/controllers/logging/page_view_log_controller_test.exs

The deviation stat when calculating balance is displayed in chobby whenever you call !balance
If the result is very high, players can get upset. With split_noobs, we do not trust the rating (17) of new players, which can lead to high deviations. This PR aims to adjust new player's ratings in the balancer so that the deviation result is smaller.
Note that the deviation result in teiserver is already a custom deviation method that is not the same as SPADS.
Also note that teiserver adjusts people's ratings already because it applies randomness from -0.5 to 0.5. So in $explain someone could have negative rating. But in chobby nobody is displayed as negative.
split_noobs doesn't apply randomness, but does adjust ratings with this PR.
```
min(
1,
(starting_uncertainty - uncertainty) / …
```

Get custom deviation result for split_noobs

---

lib/teiserver/battle/libs/balance_lib.ex
test/teiserver/battle/balance_lib_internal_test.exs

Add logs for: https://github.com/beyond-all-reason/teiserver/issues/430
This doesn't fix the bug. But will have more logs to look at.
Does a check to see if team_sizes is empty

Add logs for errors inside balance result

---

lib/teiserver/battle/balance/auto_balance.ex
lib/teiserver/battle/balance/auto_balance_types.ex
lib/teiserver/battle/balance/split_noobs.ex
lib/teiserver/battle/libs/balance_lib.ex
test/teiserver/battle/auto_balance_internal_test.exs
test/teiserver/battle/split_noobs_internal_test.exs
test/teiserver/battle/split_noobs_test.exs
test/teiserver/protocols/spring/spring_auth_async_test.exs

- Makes auto balance call split noobs when there are at least 3 parties.  
- Rename default balance to auto balance in code.
loser_picks is stricter and tends to break up parties more often than split_noobs. this was deliberate design so we don't have one stacked team versus all solos. However, preserving parties when there are at least 3 parties should be less of an issue because this means that there's a high chance both teams will have parties.
Here's examples of supporting many parties and with both teams having parties:
When logging parties change grouping from [ to (. This makes it easier to read since many use clan tags that use [].

Auto balance call split noobs when at least 3 parties

---

lib/teiserver_web/templates/moderation/action/new_with_user.html.heex

Update the "RECENT OFFENSES"/"INCIDENT SEVERITY"/"LONG RAPTOR/BOT GAME" buttons (on the New Action page), making them enable some default restrictions when when clicked.
Each of these addons only makes sense when a suspension is issued, so automatically adding the restrictions for a suspension is a minor convenience.

Update moderation template "addons" to set default restrictions.

---

lib/teiserver_web/templates/admin/user/tab_overview.html.heex

Currently, When viewing the single-user overview page ("/teiserver/admin/user/$id"), it is not immediately obvious whether or not the user has been flagged as a Smurf.
This is because, when no actions are active, the "Restrictions" section contains a single "No restrictions" entry. However, while a Smurf Link is *technically* not a restriction, it does prevent the user from logging in.
This patch updates the user overview page's "Restrictions" section as follows:
- "No restrictions" is only listed if there are no active actions AND no Smurf Link for the user.
- When the user has a Smurf Link, it is displayed in the same way as any other active actions.

Display "Smurf Link" as a restriction on user overview page.

---

lib/teiserver_web/controllers/account/session_controller.ex
test/teiserver_web/controllers/account/session_controller_test.exs

Addresses #133 
Note that tests do not verify the added log lines when an expired code is accessed (although the code path is exercised).

Correctly verify one_time_code IP address; log expired code access

---

lib/teiserver_web/views/api/o_auth/code_view.ex
test/teiserver_web/controllers/o_auth/code_controller_test.exs

Add missing parameter for oauth discovery

---

lib/teiserver/autohost.ex
lib/teiserver/autohost/registry.ex
lib/teiserver/autohost/tachyon_handler.ex
priv/tachyon/schema/autohost/status/event.json
test/support/tachyon.ex
test/teiserver_web/controllers/tachyon_controller_test.exs
test/teiserver_web/tachyon/autohost.exs

A smaller one for once. This is to handle the `autohost/status` message.
Since this is the first message that the autohost must send right after connection it should be handled before we're able to start a game.

Autohost basics

---

lib/teiserver/battle/libs/balance_lib.ex

Currently logs for loser_picks show user ids when there are parties
This PR shows names of players instead of user ids for logs
Simply go to a match on website and look at loser_picks balance logs

Fix logs for loser picks

---

test/teiserver_web/controllers/account/session_controller_test.exs

We use the guardian auth framework to assert whether a user has been signed in, rather than inspecting the HTML response. This change makes tests less brittle to HTML or other view changes.

Use Guardian.Plug to assert sign in status

---

lib/teiserver_web/router.ex
test/teiserver_web/controllers/account/security_controller_test.exs
test/teiserver_web/live/account/relationship/index_live_test.exs
test/teiserver_web/live/account/settings/index_live_test.exs
test/teiserver_web/live/admin/chat/index_live_test.exs
test/teiserver_web/live/battles/match/chat_live_test.exs
test/teiserver_web/live/battles/match/ratings_live_test.exs
test/teiserver_web/live/communication/chat/index_live_test.exs
test/teiserver_web/live/general/home/index_live_test.exs
test/teiserver_web/live/microblog/admin/post_live_test.exs
test/teiserver_web/live/microblog/admin/tag_live_test.exs
test/teiserver_web/live/microblog/blog/preference_live_test.exs
test/teiserver_web/live/moderation/overwatch/index_test.exs

As detailed in https://github.com/beyond-all-reason/teiserver/issues/175#issuecomment-2385399045, live endpoints that redirect to '/login' on mount cannot set the _redirected_to cookie. Therefore, when unlogged in users try to access a live endpoint, they will be redirected to '/login', and upon logging in be redirected to '/' instead of their original destination.
This change ensures that all live endpoints use the :protected pipeline, which can redirect users back to their original destination once they completed logging in.
Added a bunch of tests to verify that the live endpoints require authentication. Added a specific test to ensure that users are redirected back to the edit password page when they complete logging in (the original reported issue in #175).
Addresses #175

Live endpoints that require authentication are piped through the :protected pipeline

---

lib/teiserver/mix_tasks/fake_data.ex
lib/teiserver/mix_tasks/fake_playtime.ex

This PR adds two things:
1. Reduces the amount of 1-3 chevs (which are counted as noobs for split_noobs). There will now be only 1-2 noobs in a 16 player game.
2. Adds parties to fake data task
Run
```
mix teiserver.fakedata
```
Go to a match on website and you will see parties represented as dice

Add party to fake data task

---

lib/teiserver/coordinator/spads_parser.ex

Teiserver currently tracks who is the boss of a lobby by looking for known outputs from the `!boss` SPADS command.
However, an `!unboss` command was recently added to SPADS, and Teiserver currently does not recognize the output of that command. As a result, whenever the `!unboss` command is used, Teiserver's list of bosses becomes out of sync with SPADS's list.
This patch adds an additional pattern so that the output of `!unboss` is recognized and parsed.

Add pattern detection for SPADS `!unboss` command output.

---

lib/teiserver/account/libs/relationship_lib.ex
lib/teiserver_web/live/account/relationship/index.html.heex

Current relationships:
- Ignore - you can't see messages from ignored users
- Avoid - if enough people avoid someone, they can't play in that lobby
- Block - if enough people block someone, they can't join that lobby
All avoided users are currently also considered ignored and all blocked users are also considered avoided.
This PR is a simple change allowing users to Avoid or Block someone without Ignoring them

Avoided users are no longer considered ignored

---

lib/teiserver_web/live/battles/lobbies/show.ex

Inside teiserver website, when viewing the rating in lobby, it always show Large Team rating. This PR shows rating based on team size and team count.

Pick correct rating type on lobby screen

---

test/teiserver/protocols/spring/spring_auth_test.exs

- fixes flaky test
- re-enables that test
- Probably has no impact on the issues reported on https://github.com/beyond-all-reason/teiserver/issues/368 , because those error reports about red text appear to be due to the database connection throwing errors, not failing tests.
... I'm actually not sure how long it polls or what the timeout is -- if it never times out the poll would run forever, and thus the test would never finish.
_I'm open to critiques or improvements on this PR. I am open to troubleshooting and trying to fix other tests after this if this PR is accepted._

fix for flaky renameuser test using polling-until-expected-result

---

lib/teiserver/battle/balance/brute_force.ex
lib/teiserver/battle/balance/brute_force_avoid.ex
lib/teiserver/battle/balance/brute_force_avoid_types.ex
lib/teiserver/battle/balance/brute_force_types.ex
lib/teiserver/battle/balance/respect_avoids.ex
lib/teiserver/battle/balance/split_noobs.ex
test/teiserver/battle/brute_force_avoid_internal_test.exs
test/teiserver/battle/brute_force_internal_test.exs
test/teiserver/battle/brute_force_test.exs
test/teiserver/battle/respect_avoids_test.exs
test/teiserver/battle/split_noobs_internal_test.exs
test/teiserver/battle/split_noobs_test.exs

In the image below the two best players DmE and Jeff are on the same team. If we add a captain rating diff penalty then they will be split
Here is the new result:
```
"Team 1: Gmans, AbyssWatcher, AcowAdonis, Jarial, [DmE], Spaceh, fraqzilla, Pantsu_Ripper",
"Team 2: Faeton, Kaa, Zippo9, Threekey, mighty, MeowCat, Jeff, Saffir"
```
Note that this is the exact same result if we use a stdev penalty with importance of 2:
```
"Team 1: Gmans, AbyssWatcher, AcowAdonis, Jarial, [DmE], Spaceh, fraqzilla, Pantsu_Ripper",
"Team 2: Faeton, Kaa, Zippo9, Threekey, mighty, MeowCat, Jeff, Saffir"
```
See this PR for using stdev diff penalty instead:
https://github.com/beyond-all-reason/teiserver/pull/508
We can still use stdev penalty in brute_force.ex (called by split_noobs) if we want.
The score will …

Add captain diff penalty to respect avoids

---

lib/teiserver_web/live/moderation/report_user/index.ex

This PR fixes the dates on report page. To test this go to a match, then players, then report a player. Then choose ingame actions > griefing. There should be a list of matches. If there isn't a list of matches you can adjust the code to show more days. The timezone should be localised with this PR and use the user's timezone.

Fix timezone on report page

---

lib/teiserver/mix_tasks/fake_data.ex

I believe this will resolve https://github.com/beyond-all-reason/teiserver/issues/500
Not quite sure how to verify this automatically, as I don't see any unit tests for fake data, but here are some manual tests:
- Running `mix test --exclude needs_attention` only returns 2 errors locally (same as master branch)
- Searching the `account_users` table shows what I expected in the data column:
- Running a Verified Report shows only 3 unverified out of 37... I think that's the expected outcome. (EDIT: nevermind, looks like that was looking at the roles column.)
- Clicking into an arbitrary user shows their data section has a "roles" key with a list, that includes "Verified"

default generated fake_data users to be verified

---

lib/teiserver_web/live/battles/match/index.html.heex
lib/teiserver_web/live/battles/match/ratings.html.heex

The timezone is incorrect on the list page
https://discord.com/channels/549281623154229250/1297333683619106938
This PR fixes it by applying code change that is similar on other pages which is working correctly.
The correct code has a tz parameter e.g. on `/lib/teiserver_web/live/battles/match/show.html.heex` we have:
```
<div class="col">
<strong>Started:</strong> <%= date_to_str(@match.started, format: :ymd_hms, tz: @tz) %>
</div>
<div class="col">
<strong>Finished:</strong> <%= date_to_str(@match.finished, format: :ymd_hms, tz: @tz) %>
</div>
```

Fix incorrect timezone on match list page

---

lib/teiserver/account/libs/role_lib.ex
lib/teiserver/coordinator/consul_server.ex
lib/teiserver/data/cache_user.ex

- VIP role now ignores time based rename restrictions
- Removed vip_boss commands (`shuffle` was only such command, now moved to admin)
- VIP no longer contains BAR+

VIP role improvements

---

lib/teiserver/config.ex
test/support/conn_case.ex
test/support/server_case.ex
test/support/teiserver_test_lib.ex
test/teiserver/data/user_test.exs
test/teiserver_web/controllers/api/spads_controller_test.exs

A few tests are consistently failing on master, fixing that.

Fix more tests

---

mix.exs
test/teiserver/helpers/timex_helper_test.exs

This test was failing on my machine with the following (but did not fail in the GH Action build):
```
code:  assert TimexHelper.date_to_str(@today) == "2013-12-04"
left:  "2013-12-03"
right: "2013-12-04"
```
Some brief investigation showed that the time calculation was 6 hours prior; which lines up with my current timezone, America/Chicago, or UTC -6:00. 
```
code:  assert TimexHelper.date_to_str(@today, format: :ymd_hms) == "2013-12-04"
left:  "2013-12-03 18:00:00"
right: "2013-12-04"
```
Setting the timezone on the test to the same timezone specified when the initial time set up  fixed the test failure. I think it would fix the test failure for all developers west of the selected timezone of Europe/London.
(Alternative option: if there was a way to set the timezone for the container …

set timezone on timezone-unaware test

---

config/runtime.exs
lib/teiserver_web/views/api/o_auth/code_view.ex

Resolves #499 
1. If the environment variable `TEI_DOMAIN_NAME` isn't set in local dev, then the `domain_name` local in runtime.exs used the default of `"beyondallreason.info"`.
2. Even if `TEI_DOMAIN_NAME` was set, the manual string interpolation `"https://#{domain_name}"` didn't give the correct urls if TLS/SSL wasn't enabled.
3. This causes the http://localhost:4000/.well-known/oauth-authorization-server url to return incorrect endpoints.
* Use `TeiserverWeb.Endpoint.static_url()` [static_url/0 docs](https://hexdocs.pm/phoenix/Phoenix.Endpoint.html#c:static_url/0) to get the base url.
* Since the `domain_name` is set on the endpoint module with `url: [host: domain_name]`, the domain should work the exact same as before in test/prod.
* The uri scheme should also pull in correctly based …

Make OAuth discovery work locally

---

lib/teiserver/autohost.ex
lib/teiserver/autohost/registry.ex
lib/teiserver/autohost/tachyon_handler.ex
lib/teiserver/matchmaking.ex
lib/teiserver/matchmaking/pairing_room.ex
lib/teiserver/matchmaking/queue_server.ex
lib/teiserver/player.ex
lib/teiserver/player/session.ex
lib/teiserver/player/tachyon_handler.ex
lib/teiserver/tachyon/handler.ex
lib/teiserver/tachyon/schema.ex
lib/teiserver/tachyon/transport.ex
mix.exs
priv/tachyon/schema/autohost/start/response.json
test/support/fixtures/autohost.ex
test/support/tachyon.ex
test/teiserver/matchmaking/pairing_test.exs
test/teiserver_web/tachyon/autohost.exs
test/teiserver_web/tachyon/matchmaking_test.exs

Integration with [recoil-host](https://github.com/beyond-all-reason/recoil-autohost)
https://github.com/user-attachments/assets/0514001d-6a94-4779-bff5-49ee6cdde8c6
I've added a few comments after this video was recorded.

Matchmaking starts autohost

---

lib/teiserver/autohost/tachyon_handler.ex
lib/teiserver/player/tachyon_handler.ex
lib/teiserver/tachyon/handler.ex
lib/teiserver/tachyon/transport.ex

Especially the request/response cycle and timeouts. This is not perfect and may not be final. If the handler wants to send multiple message, there is no way to leverage the transport for that yet.

Centralise tachyon logic in the transport layer

---

config/config.exs
lib/teiserver/autohost/tachyon_handler.ex
lib/teiserver/matchmaking/pairing_room.ex
lib/teiserver/player/tachyon_handler.ex
lib/teiserver/tachyon/schema.ex
lib/teiserver/tachyon/schema_loader.ex
lib/teiserver/tachyon/transport.ex
priv/tachyon/schema/autohost/start/request.json
priv/tachyon/schema/battle/start/request.json
priv/tachyon/schema/definitions/allyTeam.json
priv/tachyon/schema/definitions/bot.json
priv/tachyon/schema/definitions/customStartScriptProperties.json
priv/tachyon/schema/definitions/player.json
priv/tachyon/schema/definitions/startBox.json
priv/tachyon/schema/definitions/startPosType.json
priv/tachyon/schema/definitions/team.json
priv/tachyon/schema/definitions/userId.json
priv/tachyon/schema/matchmaking/cancel/response.json
priv/tachyon/schema/matchmaking/cancelled/event.json
priv/tachyon/schema/matchmaking/foundUpdate/event.json
priv/tachyon/schema/matchmaking/list/response.json
priv/tachyon/schema/matchmaking/lost/event.json
priv/tachyon/schema/matchmaking/queue/response.json
priv/tachyon/schema/matchmaking/ready/response.json
test/support/tachyon.ex
test/teiserver_web/tachyon/matchmaking_test.exs
test/teiserver_web/tachyon/session_test.exs

Ensure that the tachyon messages sent by the server conform to the json schemas.
And some light refactoring in the first 3 commits.
The schemas added here (the vast majority of the scary +617) are taken from the [tachyon repo](https://github.com/beyond-all-reason/tachyon/tree/master/schema)

Validate messages in tests

---

lib/teiserver/game/libs/match_rating_lib.ex

Rating system should be primarily used to rate players with the goal of achieving better balanced teams resulting in higher quality matches.
The only thing that should matter is the final outcome of the match, it should not be used as a way to punish undesired behaviour such as early resigning. Bad strategies such as early resigning should naturally lead to worse team performance reducing the possibility of victory,
Currently losses always result in rating reduction, however you only get increased rating if you were present for at least 90% of the match (check `Teiserver.Battle.MatchLib.calculate_exit_status` for details). 
This also makes it possible for some players and smurfs to intentionally keep their ratings low by resigning early.
**This PR changes the rating logic to always rate …

Rate early leavers

---

lib/teiserver/battle/libs/balance_lib.ex
lib/teiserver_web/live/battles/match/show.html.heex

The game_rating_logs table in database stores the postmatch values.
Thefore when we use the balance tab to view past match data, we need to adjust the postmatch data so that it becomes prematch data.
Find any past match. Look at the rating of a single player in that match. This is their prematch rating. Next select the balance tab and view the logs for loser_picks balance. The rating of the player should match the prematch rating.

Fix prematch ratings on balance tab

---

lib/teiserver/account/schemas/rating.ex
lib/teiserver/game/libs/match_rating_lib.ex
priv/repo/migrations/20241212224758_add_num_matches_column.exs
test/teiserver/game/libs/match_rating_lib_test.exs

After running
```
mix ecto.migrate
```
This will add a new num_matches column to the database and also populate it with values. Whenever a match is rated, the num_matches numer will increase by one, with the exception that if it is a rating override, the num_matches will stay the same.
The num_matches column can be used in the **future** for many possible use cases:
```
min(1, num_matches/30) * skill
```
This idea has been approved by Marek: [Source](https://www.reddit.com/r/beyondallreason/comments/1h9fc0v/comment/m10eh2r/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)
This means that new players start at 0 and converge towards their skill over time. We won't have tons of people stuck at 0 due to negative ratings since there's no more subtraction …

Add num_matches column

---

lib/teiserver/account/libs/account_test_lib.ex
lib/teiserver/account/libs/relationship_lib.ex
lib/teiserver_web/live/account/relationship/index.ex
lib/teiserver_web/live/account/relationship/index.html.heex
lib/teiserver_web/router.ex
test/teiserver/account/relationship_lib_test.exs
test/teiserver_web/live/account/relationship/index_live_test.exs

The purpose of this is to help fix Kobold's error https://ptb.discord.com/channels/549281623154229250/1310908634036703302
This user has 1000 avoids/blocks/ignores. It is basically difficult for him to trim that list down and it causing issues.

Purge inactive friends and avoids

---

test/support/tachyon.ex

to accommodate slower processors or variable compute availability. 
Per conversation with BlackMelon and jauggy on Discord.
This also addresses some timeout errors I was seeing on my (slow) machine when running `mix test test/teiserver_web/tachyon/matchmaking_test.exs`

lengthen tachyon test client timeout 

---

lib/teiserver/microblog/schemas/post.ex
lib/teiserver_web/live/microblog/admin/post/post_form_component.ex
lib/teiserver_web/live/microblog/blog/index.html.heex
priv/repo/migrations/20241229013049_add_microblog_poster_alias.exs
test/teiserver_web/live/microblog/post_form_component_test.exs

This feature is useful for people who have a contributor name that is different from their in-game name. Currently when you make a blogpost, it uses your ingame name. This feature allows you to set a contributor alias (display name) to show for your blog post. The userid is still saved in the database so if there is any abuse (like impersonation), an admin would know.
Local testing
```
mix ecto.migrate
```
This will create a new column in the database.
Login to website and go to Blog > Blog Admin
Fill in the form. You will notice the Post button is disabled. That's because you must attach a tag. If there are no tags, go to the Tags tab and create one. Then you can press post.
Check the post appears. 
You can retest using a different author alias or even a blank contributor alias (will use …

Add contributor alias to blost post

---

lib/teiserver_web/live/battles/match/show.ex
lib/teiserver_web/live/battles/match/show.html.heex

Removed units produced column (because useless)
Instead added uncertainty column. This is the prematch value.

Add uncertainty to player page

---

config/runtime.exs
lib/teiserver_web/views/api/o_auth/code_view.ex

The discovery endpoint includes port `8888` in the URLs.
https://server4.beyondallreason.info/.well-known/oauth-authorization-server
Current deployment response:
This issue was introduced by https://github.com/beyond-all-reason/teiserver/pull/523 (sorry), which fixed the urls for local development. However, the server port is `8888` internally when deployed, and the url helper methods aren't aware of the final deployed port.
This PR fixes the prod endpoint while keeping the localhost functionality.

Fix oauth discovery

---

.github/workflows/tests.yml
coveralls.json
documents/guides/testing.md
scripts/show_test_coverage_for_files_changed_in_last_month.sh

Admittedly, I like writing tests and I think writing or fixing a few tests is a good way to get to know a codebase. So I've been poking around the failing tests in Teiserver in order to learn my way around the codebase.
I realized, though, that another way to think about the problem of improving test coverage (without boiling the ocean) is to focus on the test coverage of recently changed files.
So, as an experiment, I wrote up this script to filter "test coverage per-file" with "only files changed in the last month". I think I will find it useful. Maybe it will be useful to others.
Example output:
```
...(end of actual test run output)...
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
[os_mon] memory supervisor port (memsup): Erlang has closed
COV    FILE …
```

script to show test coverage for files that changed in the last month

---

lib/teiserver/player/session.ex

Before this change, when a user disconnect abruptly, the session would linger. If the user then reconnect before the session terminates, it would not register with the new session, and the session would get terminated as if the user did not reconnect.

Correctly reuse the session

---

lib/teiserver/battle/balance/split_noobs.ex
test/teiserver/battle/split_noobs_internal_test.exs
test/teiserver/battle/split_noobs_test.exs

This will simply add ratings to $explain for split_noobs. 
```
"Perform brute force with the following players to get the best score.",
"Players: kyutoryu (9.0), fbots1998 (2.8), jauggy (20.5), Aposis (20.4), [DTG]BamBin0 (20.1), reddragon2010 (18.4), Noody (17.6), SLOPPYGAGGER (8.9), MaTThiuS_82 (8.3), barmalev (3.6)"
```
The numbers in brackets are their ratings. 
I'm trying to understand why the ratings don't add up to team rating in this bug:
https://discord.com/channels/549281623154229250/1332129520538615818

Add more logs to explain

---

lib/teiserver/game/servers/balancer_server.ex
test/teiserver/game/balancer_server_test.exs

The balancer will sometimes use large team ratings even if it is a small team game. This is a potential fix. In the old code, team size was calculated as the largest team size of all teams. So if you were in a lobby with 6 players on team 1, then 4 players on team 2, it would use large team ratings. However, this is wrong since after balancing, the teams would become 5v5 and should be small teams.
The calculation should simply divide players by team_count rounded up.

Fix team size calculation for balancer server

---

lib/teiserver/game/libs/match_rating_lib.ex
test/teiserver/game/libs/match_rating_lib_test.exs

When rating a match, num_matches is updated in two tables:
1. teiserver_account_ratings
2. teiserver_game_rating_logs
The update to the second table was missing and is now fixed

Fix num matches not appearing

---

lib/teiserver_web/live/account/profile/accolades.ex
lib/teiserver_web/live/account/profile/overview.ex
test/teiserver_web/live/account/profile/overview_test.exs

There is an error that occurs:
```
** (exit) an exception was raised:
** (KeyError) key :id not found in: nil
If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map
(teiserver 0.1.0) lib/teiserver_web/live/account/profile/overview.ex:366: TeiserverWeb.Account.ProfileLive.Overview.assign_accolade_notification/1
(teiserver 0.1.0) lib/teiserver_web/live/account/profile/overview.ex:38: TeiserverWeb.Account.ProfileLive.Overview.mount/3
(phoenix_live_view 0.19.3) lib/phoenix_live_view/utils.ex:394: anonymous fn/6 in Phoenix.LiveView.Utils.maybe_call_live_view_mount!/5
(telemetry 1.3.0) /build/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
(phoenix_live_view 0.19.3) lib/phoenix_live_view/static.ex:278: …
```

Fix error when viewing profile when not logged in

---

documents/guides/local_setup.md
lib/teiserver/mix_tasks/gen_token.ex
lib/teiserver/mix_tasks/tachyon_setup.ex
lib/teiserver/o_auth/queries/application_query.ex
lib/teiserver/o_auth/tasks/gen_token.ex
lib/teiserver/tachyon/tasks/setup_apps.ex
lib/teiserver_web/components/core_components.ex
lib/teiserver_web/components/o_auth_application/application_form.ex
lib/teiserver_web/controllers/admin/o_auth_application_controller.ex
lib/teiserver_web/templates/admin/bot/show.html.heex
lib/teiserver_web/templates/admin/o_auth_application/edit.html.heex
lib/teiserver_web/templates/admin/o_auth_application/new.html.heex
test/teiserver/o_auth/gen_token_test.exs
test/teiserver/tachyon/tasks/setup_apps_setup.exs
test/teiserver_web/controllers/admin/o_auth_application_controller_test.exs

A few things to make our life easier around oauth apps.
* a mix task to setup the 2 required applications and the associated doc
* a better UI to manage scopes, see screenshots

Nicer oauth scopes UI

---

lib/teiserver_web/controllers/admin/user_controller.ex

Resolves issue #553 
List of users goes from 
to

Admin Quality-of-Life feature: deduplicated the list of users when using the quicksearch

---

config/config.exs
lib/teiserver/application.ex
lib/teiserver/autohost.ex
lib/teiserver/autohost/registry.ex
lib/teiserver/autohost/tachyon_handler.ex
lib/teiserver/matchmaking/pairing_room.ex
lib/teiserver/tachyon/system.ex
lib/teiserver/tachyon_battle.ex
lib/teiserver/tachyon_battle/battle.ex
lib/teiserver/tachyon_battle/registry.ex
lib/teiserver/tachyon_battle/supervisor.ex
lib/teiserver/tachyon_battle/system.ex
lib/teiserver/tachyon_battle/types.ex
test/support/tachyon.ex
test/teiserver/autohost/autohost_test.exs
test/teiserver/tachyon_battle/battle_test.exs
test/teiserver_web/tachyon/battle_test.exs
test/teiserver_web/tachyon/matchmaking_test.exs

Add a system similar to the existing battles. A tree of dynamic processes that are tied to an ongoing battle with an autohost.
The goal is for these process to handle messages from autohost, right now they do nothing.

Battle processes

---

lib/teiserver/player.ex
lib/teiserver/player/session_registry.ex
lib/teiserver/player/tachyon_handler.ex
priv/tachyon/schema/system/serverStats/request.json
priv/tachyon/schema/system/serverStats/response.json
test/support/tachyon.ex
test/teiserver_web/tachyon/system_test.exs

Tachyon system/serverStats

---

lib/teiserver/player/session.ex
test/support/tachyon.ex
test/teiserver_web/tachyon/session_test.exs

Make real sure the connection and the sessions are both gone after tests.
And it turn out that some tests were not using `Tachyon.connect`, so fixed these as well.

Ensure test cleanup sessions

---

test/support/tachyon.ex
test/teiserver_web/controllers/tachyon_controller_test.exs

Without the second commit, the following command would fail:
`mix test --exclude needs_attention test/teiserver_web/ --seed 477485`

More session flakes fix

---

lib/teiserver/account/libs/accolade_lib.ex
lib/teiserver/account/libs/badge_type_lib.ex
lib/teiserver/account/schemas/badge_type.ex
lib/teiserver_web/live/battles/match/show.ex
lib/teiserver_web/live/battles/match/show.html.heex
lib/teiserver_web/templates/admin/badge_type/form.html.heex
lib/teiserver_web/templates/admin/badge_type/index.html.heex
lib/teiserver_web/views/admin/badge_type_view.ex
priv/repo/migrations/20250206221410_add_accolade_restriction.exs

This PR allows the admin to restrict certain accolades to ally or enemy only. By default restriction is set to null which means any.
The migration script will do the following:
1. Add a new column to teiserver_account_badge_types: restriction
2. Add a constraint such that this column can only by NULL, "Ally", or "Enemy"
3. Update the "Good Teammate" accolade so that it is restricted to Ally (if it exists already). This can still be changed by the Admin via the website.
Go to http://localhost:4000/teiserver/admin/badge_types
and you should see a new column called restriction. You can edit an accolade's restriction.
For example, if Good Teammate is ally only, then you cannot give this accolade in a match where you weren't the ally of the person you are gifting to.

Allow admin to restrict certain accolades to Ally or Enemy only

---

lib/teiserver/battle/balance/auto_balance.ex

In the past I suggested using split_noobs when at least three parties. I think now that we have added standard deviation importance to split_noobs it's less risky to use it for more circumstances. This PR makes it so that if there are at least two parties, split_noobs will be used (must be two teams).
This is a sample match where split_noobs didn't keep both parties because it was trying to keep standard deviation diff close: 
https://server4.beyondallreason.info/battle/4096321/balance
respect_avoids did keep both parties together, but the standard deviation diff was probably too large for split_noobs to like.
I think it's ok and shouldn't be that risky. But maybe we see first how this goes.

Update auto_balance to use split_noobs when at least 2 parties

---

lib/teiserver/battle/balance/auto_balance.ex
lib/teiserver/battle/balance/auto_balance_types.ex
test/teiserver/battle/auto_balance_internal_test.exs

There is demand for respect_avoids to be the default algo:
https://ptb.discord.com/channels/549281623154229250/1297988341756596314
However, respect_avoids can potentially allow op parties like this:
Team 1: 0, 0, 0, 50, 50, 50
Team 2: 25, 25, 25, 25, 25, 25
Where (50,50,50) are in the same party.
This PR will make it so auto balance will pick `respect_avoids` when there are no op parties. An op party exists if the two best players in the lobby are in the same party. 
Here is an example match where there was not an op party, and if `respect_avoids` was chosen, both parties would have been kept:
https://server4.beyondallreason.info/battle/4096321/balance

Have auto balance choose respect_avoids when no op party

---

lib/teiserver/account/schemas/rating.ex
lib/teiserver/game/libs/match_rating_lib.ex
priv/repo/migrations/20250220221332_add_num_wins.exs
test/teiserver/game/libs/match_rating_lib_test.exs

One of the feedback from Borg King about using a provisional rating was this:
> I like the simplicity of this idea but I suspect there are side effects of it, as you are applying a linear filter to a player's skill, even if they are actually quite good. Happy to explore this in more detail by looking at some examples in the ratings data
https://ptb.discord.com/channels/549281623154229250/643197947441315840/1335225491191369851
If someone is a smurf and actually good, we could make them lose their provisional rating faster by basing the provisional rating on num_wins rather than num_matches (or do a combination of both). In Counterstrike for example, you get your true rating after winning 10 matches. So a smurf with a 100% win rate gets to unlock their rating faster than a bad player. In …

Add num_wins column to ratings table

---

lib/teiserver/asset.ex
lib/teiserver/asset/queries/map_queries.ex
lib/teiserver/matchmaking/pairing_room.ex
lib/teiserver/matchmaking/queue_server.ex
lib/teiserver/matchmaking/queue_supervisor.ex
lib/teiserver/player/tachyon_handler.ex
priv/tachyon/schema/matchmaking/list/request.json
priv/tachyon/schema/matchmaking/list/response.json
test/support/fixtures/asset.ex
test/teiserver/matchmaking/queue_test.exs
test/teiserver_web/tachyon/matchmaking_test.exs

Resolves #591 
Additionally added games and engines to the queue process and their selection to pairing room, passing them to start_script and showing them in `matchmaking/list`

User map pool, games and engines in matchmaking

---

lib/teiserver/config.ex
lib/teiserver/game/libs/match_rating_lib.ex
lib/teiserver/libs/teiserver_configs.ex
test/teiserver/game/libs/match_rating_lib_test.exs

Tau is configurable by admin in Site Config -> Lobby section
The default value of tau is unchanged (which is 1/3)
Also adding in prevent_sigma_increase to true

Make tau configurable by admin

---

lib/teiserver/data/cache_user.ex
lib/teiserver/lobby/libs/chat_lib.ex

`!joinas` allows players to join as another player or spectator in an active games, unfortunately it has been used by some players to join as other players without their approval and sabotage them. There was code in place that was supposed to replace all `!joinas` commands with `!cv joinas` which would call a vote when calling the command, however this code only covered the lowercase `!joinas`, it could be bypassed by different word capitalisations (e.g `!joinAs`).
These changes fix this and furthermore replace all `!joinas` command variants with `!joinas spec`, no longer allowing joining as another player.

Replace all joinsas with joinas spec

---

lib/teiserver/account.ex
lib/teiserver/account/libs/friend_request_lib.ex
lib/teiserver/account/queries/friend_request_queries.ex
lib/teiserver/player/session.ex
lib/teiserver/player/tachyon_handler.ex
priv/tachyon/schema/friend/acceptRequest/request.json
priv/tachyon/schema/friend/acceptRequest/response.json
priv/tachyon/schema/friend/cancelRequest/request.json
priv/tachyon/schema/friend/cancelRequest/response.json
priv/tachyon/schema/friend/list/request.json
priv/tachyon/schema/friend/list/response.json
priv/tachyon/schema/friend/rejectRequest/request.json
priv/tachyon/schema/friend/rejectRequest/response.json
priv/tachyon/schema/friend/remove/request.json
priv/tachyon/schema/friend/remove/response.json
priv/tachyon/schema/friend/removed/event.json
priv/tachyon/schema/friend/requestAccepted/event.json
priv/tachyon/schema/friend/requestCancelled/event.json
priv/tachyon/schema/friend/requestReceived/event.json
priv/tachyon/schema/friend/requestRejected/event.json
priv/tachyon/schema/friend/sendRequest/request.json
priv/tachyon/schema/friend/sendRequest/response.json
test/support/fixtures/account/account_fixtures.ex
test/support/tachyon.ex
test/teiserver/account/friend_request_lib_test.exs
test/teiserver_web/tachyon/friend_test.exs

This should cover the messages to [handle friends](https://github.com/beyond-all-reason/teiserver/issues/619).
I noticed it's getting a bit verbose sending error responses, I'll refactor that and put it as part of the [handler](https://github.com/beyond-all-reason/teiserver/blob/master/lib/teiserver/tachyon/handler.ex) behaviour, but that can be done in another PR.

Tachyon friends

---

lib/teiserver/account.ex
lib/teiserver/account/libs/rating_lib.ex
lib/teiserver/account/schemas/rating.ex
lib/teiserver/account/tasks/smurf_merge_task.ex
lib/teiserver/game/libs/match_rating_lib.ex
lib/teiserver/game/schemas/rating_log.ex
lib/teiserver/libs/teiserver_configs.ex
lib/teiserver_web/controllers/admin/user_controller.ex
priv/repo/migrations/20250311104815_add_seasons.exs
test/teiserver_web/controllers/api/spads_controller_test.exs

Adds a new column `season` to account ratings and rating logs tables. Keeping it an integer for simplicity (new season table with additional season data can be added in the future if necessary).
I was planning to add a season selector to the leaderboard page, but ran into some issues so decided to keep it as simple as possible for now, additional features can be added later.
Another idea is to also have a new season management page through which new seasons could be added and activated while old ones could show all kinds of seasonal statistics (e.g. number of matches and players, rating distributions)

Add season to ratings

---

lib/teiserver/account.ex
lib/teiserver/account/reports/leaderboard_report.ex
lib/teiserver/account/reports/tournament_report.ex
lib/teiserver/account/tasks/smurf_merge_task.ex
lib/teiserver/coordinator/coordinator_commands.ex
lib/teiserver/game/exports/player_ratings_export.ex
lib/teiserver/game/libs/match_rating_lib.ex
lib/teiserver/game/libs/rating_log_lib.ex
lib/teiserver_web/controllers/admin/user_controller.ex
lib/teiserver_web/controllers/battle/match_controller.ex
lib/teiserver_web/controllers/battle/ratings_controller.ex
lib/teiserver_web/live/battles/match/ratings.ex
test/teiserver/game/libs/match_rating_lib_test.exs

Continuation to https://github.com/beyond-all-reason/teiserver/pull/617.
Adding season filter to all `list_ratings` because `teiserver_account_ratings` used to hold only one rating per player.

Add rating seasons

---

test/teiserver_web/tachyon/user_test.exs

Doing an assert `%{foo: x} = bar` binds `x`, but doesn't check for equality. For that, the variable needs to be pinned.

Fix warnings and unpinned data

---

lib/teiserver/game/servers/balancer_server.ex
test/teiserver/battle/balance_lib_internal_test.exs
test/teiserver/game/balancer_server_test.exs

Fixes the unbounded memory consumption behavior described by #576 ; adds tests for the changed function calls.
Now BalancerServer will only retain the most recent balance result, so long as it has not been cleared by another operation like `:reset_hashes` or `:set`.
Probably needs a spin on the testing server to verify we haven't broken a function call that was depending on `handle_call(:report_state)` returning the number of hashes, but other than that I think I've written all the unit-tests for all of the parts that changed.

Remove deep caching hashmap in balancer server

---

lib/teiserver/account/servers/party_server.ex
lib/teiserver/protocols/spring/spring_party_in.ex
lib/teiserver/protocols/spring/spring_party_out.ex
test/teiserver/protocols/spring/spring_party_test.exs

bugs [reported by masterbel](https://discord.com/channels/549281623154229250/1341480967063339110/1354083844340322315)
I think I've found a server bug in the parties implementation, where a player receives an incorrect command when a party they are invited to is destroyed.
Steps to reproduce:
testacc200 logs on and creates a party
testacc201 logs on and creates a party
testacc201 invites testacc200 to their party
testacc201 leaves their party
testacc201 incorrectly receives s.party.left_party 01JQ6PVVF3265QFC3R5VXP76D6 testacc200 rather than either s.party.left_party 01JQ6PVVF3265QFC3R5VXP76D6 testacc201 or s.party.invite_cancelled 01JQ6PVVF3265QFC3R5VXP76D6 testacc200
This occurs only when the last member of the party leaves, and regardless of how many invites there are to that party. …

Fix invite broadcast

---

lib/teiserver/mix_tasks/fake_data.ex
lib/teiserver_web/live/battles/match/show.ex
lib/teiserver_web/live/battles/match/show.html.heex
lib/teiserver_web/templates/battle/match/tab_players.html.heex
test/teiserver_web/live/battles/match/show_live_test.exs

Issue: [#583](https://github.com/beyond-all-reason/teiserver/issues/583)
Features:
- Now shows team totals for damage, metal, and energy when teams have multiple players
Tests cover team games (2v2), uneven teams (2v1), duels (1v1), and free-for-all games (1v1v1).
No team stats shown for single player teams:

Add team stat totals to match results display

---

lib/teiserver/account.ex
lib/teiserver/account/libs/user_lib.ex
lib/teiserver/player/session.ex
lib/teiserver/player/tachyon_handler.ex
priv/tachyon/schema/user/subscribeUpdates/request.json
priv/tachyon/schema/user/subscribeUpdates/response.json
priv/tachyon/schema/user/unsubscribeUpdates/request.json
priv/tachyon/schema/user/unsubscribeUpdates/response.json
test/support/tachyon.ex
test/teiserver/player/session_test.exs
test/teiserver_web/tachyon/user_test.exs

Basics for [user/updated](https://github.com/beyond-all-reason/tachyon/blob/master/docs/schema/user.md#updated) events. For now, only supports the `status: menu | offline` bits.

User subscription events

---

config/config.exs

Some larger error logs are getting truncated before the important part or the entire error is outputted. This doubles the default limit.

Increase error log truncuation limit

---

lib/teiserver/account/servers/party_server.ex
test/teiserver/protocols/spring/spring_party_test.exs

It was possible that subscriber would receive the `close` message and unsubscribe from the party topic before the message about cancel invite is sent. Now, unsubscribing from the topic is only done after no more message is sent on the topic.

Fix a race condition when closing a party.

---

lib/teiserver/application.ex
lib/teiserver/asset/queries/map_queries.ex
lib/teiserver/matchmaking/queue_supervisor.ex
test/support/conn_case.ex
test/support/data_case.ex
test/support/server_case.ex
test/support/tachyon.ex
test/teiserver/account/client_server_test.exs
test/teiserver/autohost/autohost_test.exs
test/teiserver/battle/lobby_server_test.exs
test/teiserver/matchmaking/queue_sync_test.exs
test/teiserver/matchmaking/queue_test.exs
test/teiserver/player/session_test.exs
test/teiserver/protocols/spring/spring_telemetry_test.exs
test/teiserver/tachyon_battle/battle_test.exs
test/teiserver_web/controllers/account/general_controller_test.exs
test/teiserver_web/controllers/api/spads_controller_test.exs
test/teiserver_web/live/battle_live_test.exs
test/teiserver_web/live/battles/match/chat_live_test.exs
test/teiserver_web/live/microblog/admin/post_live_test.exs
test/teiserver_web/tachyon/matchmaking_test.exs

As I was working on something else I encountered an issue where restarting a supervisor during a test would cause some issues. I tried to make it so that each test would run with a brand new supervision tree but encountered some errors with that, so I reduced it to only the tachyon system which is fairly self contained.
And also added a few other minor improvements, running the tests hundreds of time tend to unearth some issues.

Test improvements

---

lib/teiserver/asset.ex
lib/teiserver/matchmaking.ex
lib/teiserver/matchmaking/queue_server.ex
lib/teiserver/matchmaking/queue_supervisor.ex
lib/teiserver/matchmaking/system.ex
lib/teiserver/player/session.ex
test/teiserver/matchmaking/queue_test.exs
test/teiserver_web/tachyon/matchmaking_test.exs

This ties some lose ends:
* robust matchmaking: when a queue dies, the player's state will be accordingly reset
* restart queues when asset changes. This also has the effect that queuing player will get kicked out, which is what we want. Maybe later we can add some additional logic to avoid too many restarts, but I'm not sure how important it's going to be, and this simpler version will work fine for now.

Asset mm restart

---

lib/teiserver/account.ex
lib/teiserver/account/libs/rating_lib.ex
lib/teiserver_web/controllers/admin/user_controller.ex
lib/teiserver_web/controllers/api/public_controller.ex

Unfortunately I missed an important bug - leaderboards for previous seasons were stil using activity time relative to today and so after 35 days no matches would be shown. This PR fixes the bug by first finding the time of the newest rating in the older season and then calculating 35 days from that to use as the activity time.

Fix leaderboard activity for previous seasons

---

lib/teiserver/application.ex
lib/teiserver/matchmaking.ex
lib/teiserver/matchmaking/queue_supervisor.ex
lib/teiserver/matchmaking/system.ex
test/support/server_case.ex
test/support/tachyon.ex
test/teiserver/asset/engine_test.exs
test/teiserver/asset/game_test.exs

Instead of relying on different configuration of the app for test vs the rest, always start the same app, and restart the trees between tests. Ideally, we would restart then entire application tree, but last time I checked, there was some issues with the tcp servers.

Restart tachyon system between sync tests

---

lib/teiserver/tcp/spring/spring_tcp_server.ex

Sets [max_heap_size](https://www.erlang.org/docs/23/man/erlang#process_flag_max_heap_size) for SpringTcpServer to ~20 MB
For info on how Elixir's GC works https://www.erlang.org/doc/apps/erts/garbagecollection. 
If my understanding is correct, GC will attempt to collect when the process reaches the `max_heap_size` and if it isn't successful in reducing the heap size, the process will be killed (configurable as well, default true).

Add max heap size to SpringTcpServer

---

lib/teiserver/messaging.ex
lib/teiserver/messaging/message.ex
lib/teiserver/party.ex
lib/teiserver/party/server.ex
lib/teiserver/player/session.ex
lib/teiserver/player/tachyon_handler.ex
priv/tachyon/schema/messaging/received/event.json
priv/tachyon/schema/messaging/send/request.json
test/support/tachyon.ex
test/teiserver_web/tachyon/messaging_test.exs

Add support for the target `party` for messaging. Send the message to all other member of the sender's current party.

Messaging for parties

---

lib/teiserver/account/libs/role_lib.ex

Fixes the bug where moderators would lose their own `Moderator` role when editing their other roles or properties.

Fix moderator role management

---

lib/teiserver/data/cache_user.ex

New registration improvements from #637 use random colour and icon if nothing is set specifically. This sets the previous default icon and colour and makes it easier to notice special users like contributors or moderators.

Add default icon and colour to user registration

---

.github/ISSUE_TEMPLATE/1-bug_report.yml
.github/ISSUE_TEMPLATE/2-feature_request.yml

Uses Github `types` instead of `label` for classifying issues.

Change issue template labels to types

---

lib/teiserver/libs/teiserver_configs.ex
lib/teiserver/tcp/spring/spring_tcp_server.ex

Added config for `max_heap_size` on spring TCP server, increased default to 100 MB for now.

Add configuration for SpringTCPServer max_heap_size

---

lib/teiserver/application.ex
lib/teiserver/bridge/discord_supervisor.ex
lib/teiserver/bridge/discord_system.ex
lib/teiserver/chat/chat_room_cache.ex

Should address the startup issue in #237 
- Moves Nostrum.Application / API into a DynamicSupervisor that basically just logs any Nostrum errors or crashes
- This allows Teiserver to start despite Discord API failure
- (I simulated that by manually induced failure by using an invalid access token)
- This would make Discord integration a one-shot attempt. After teiserver startup Discord connection would not be re-attempted until the next teiserver restart. 
- Connection appears to succeed as expected when Nostrum is provided correct Discord credential information: 
>  ![image](https://github.com/user-attachments/assets/4026521c-3cad-40ea-a6b3-4884c5ff016a)
- Does not retain a deliberate queue of messages to eventually send to discord, but _could_ be a source of slow memory leaks or …

address "Application can't start when discord is unavailable"

---

lib/teiserver_web/templates/battle/match/ratings_graph.html.heex

`curveCatmullRom` was chosen over `curveMonotoneX`.
`curveMonotoneX` give better looking curve, however it introduces a minor visual glitch where the "middle of uncertainty" skill line doesn't follow the edge of "bottom part of confidence interval" and leaves a little gap, see image.
If we wanna use the nicer looking `curveMonotoneX`, we could also omit the "middle of uncertainty" skill line, since it is barely visible anyway and the edge of the two areas accomplishes the same visual feat.

change curve algorihm for rating graph to curveCatmullRom to fix visual glitches

---

.githooks/pre-commit
documents/guides/local_setup.md

The `.githooks` directory contains a `pre-commit` Git hook that will run `mix format` on staged files before they get commited.
To use this (and other Git hooks) you have to first make them executable with
```
chmod +x .githooks/pre-commit
```
then use the following command to change the location where Git looks for hook scripts (from the default `.git/hooks`) to the `.githooks` directory
```
git config core.hooksPath .githooks
```

Add .githooks with mix format pre commit hook

---

lib/teiserver/account/accolades/accolade_bot_server.ex
lib/teiserver/account/libs/account_test_lib.ex
lib/teiserver/battle/servers/match_monitor_server.ex
lib/teiserver/bridge/bridge_server.ex
lib/teiserver/coordinator/coordinator_server.ex
test/teiserver_web/controllers/admin/user_controller_test.exs

Working on #713, @geekingfrog noticed a bunch of non-flakey test failures.  I _think_ this resolves that issue without rolling back the change introduced to add email validation to the user schema in #709 
- Update AccountTestLib.user_fixture() to use valid email addresses with @test.local domain
- Fix admin user controller tests to use valid email addresses
- Fix all bot account emails to use valid domains:
- Coordinator: coordinator@teiserver.local
- Bridge: bridge@teiserver.local
- Match Monitor: match_monitor@teiserver.local
- Accolade: accolades_bot@teiserver.local
- This resolves test failures caused by email validation introduced in PR #709

Fix email validation in tests and bot accounts after PR #709

---

lib/teiserver/o_auth.ex
lib/teiserver_web/controllers/api/admin/user_controller.ex

Turn out the @spec for create token was incorrect.
That wasn't caught earlier because other call sites used `Keyword.put` on the options, and dialyzer doesn't understand that.

Fix admin api to create tokens

---

lib/teiserver/autohost.ex
lib/teiserver/autohost/tachyon_handler.ex
lib/teiserver/player.ex
lib/teiserver/player/session.ex
lib/teiserver/tachyon/system.ex
lib/teiserver/tachyon/transport.ex
lib/teiserver/tachyon_battle.ex
lib/teiserver/tachyon_battle/battle.ex
priv/tachyon/schema/autohost/kill/request.json
priv/tachyon/schema/autohost/kill/response.json
priv/tachyon/schema/autohost/sendMessage/request.json
priv/tachyon/schema/autohost/sendMessage/response.json
test/support/tachyon.ex
test/teiserver/autohost/autohost_test.exs
test/teiserver/tachyon_battle/battle_test.exs
test/teiserver_web/tachyon/autohost_test.exs
test/teiserver_web/tachyon/battle_test.exs

This is the start of handling commands from players and relay them to autohost.
It requires https://github.com/beyond-all-reason/recoil-autohost/issues/21 to be fixed to actually work.
Couple of points here:
* I've refactored the way to issue request from server to client and block until client responds. I think it'll require a bit more work to handle error response, but we can see when we start copy/pasting too much code.
* I changed the order of startup between autohost and battles. That means battle can freely `call` into autohosts, but autohosts should only `cast` to battle. Following this rule (based on init order in the supervision tree) should prevent deadlocks.
* I added the `send_message` logic. Turn out it's irrelevant when it comes to stopping a battle, but we'll need that …

Kill battle with `!stop`

---

lib/teiserver_web/controllers/admin/user_controller.ex

GDPR clean was not updating user with new randomised name and email due to email validation failing,
Specifically, user `:script` changeset, `Teiserver.CacheUser.valid_email?` was returning false because the GDPR clean email didn't contain a dot.

Fix GDPR clean not updating user due to invalid email

---

lib/teiserver/matchmaking.ex
lib/teiserver/matchmaking/queue_server.ex
lib/teiserver_web/live/admin/admin_components.ex
lib/teiserver_web/live/admin/matchmaking/index.ex
lib/teiserver_web/live/admin/matchmaking/index.html.heex
lib/teiserver_web/router.ex
lib/teiserver_web/templates/admin/general/index.html.heex
test/teiserver/matchmaking/queue_test.exs
test/teiserver_web/live/admin/matchmaking/index_test.exs

Adding a simple admin dashboard for viewing matchmaking queues at `/admin/matchmaking`
Closes #684

simple matchmaking admin dashboard

---

test/support/tachyon.ex

Running this locally drastically reduce the amount of noise related to processes doing their things while the sql sandbox is no more.

Attempt to reduce noisy test output

---

lib/teiserver/application.ex
lib/teiserver/coordinator.ex
lib/teiserver/lobby/libs/lobby_lib.ex
lib/teiserver/protocols/spring/spring_battle_out.ex
lib/teiserver/protocols/spring/spring_out.ex

Fix for crashes related to #705 
Discord convo: https://discord.com/channels/549281623154229250/564591092360675328/1402703973617635481
Error logs showed KeyError crashes when accessing `:host_teamsize` from nil values:
```
(KeyError) key :host_teamsize not found in: nil
(teiserver 0.1.0) lib/teiserver/lobby/libs/lobby_lib.ex:554: Teiserver.Lobby.LobbyLib.get_team_config/1
```
Also found login timeouts due to blocking `get_team_config(:all)` calls.
- Added `case` blocks to handle nil returns from `Teiserver.Coordinator.get_team_config/1`
- Prevents KeyError when consul servers don't exist
- Moved `get_team_config(:all)` call to async task in `spring_out.ex`
- Prevents login timeouts
- Added nil check in `spring_tcp_server.ex` before calling `SpringOut.reply`
- Added nil guard in …

Fix s.battle.teams crashes

---

lib/teiserver/account/caches/user_cache_lib.ex
lib/teiserver/account/libs/account_test_lib.ex
lib/teiserver/account/libs/relationship_lib.ex
lib/teiserver/account/reports/retention_report.ex
lib/teiserver/account/schemas/user.ex
lib/teiserver/data/cache_user.ex
lib/teiserver_web/controllers/admin/user_controller.ex
lib/teiserver_web/live/account/relationship/index.ex
lib/teiserver_web/templates/admin/user/smurf_list.html.heex
lib/teiserver_web/templates/admin/user/tab_details.html.heex
lib/teiserver_web/templates/report/report/ban_evasion.html.heex
lib/teiserver_web/templates/report/report/new_smurf.html.heex
priv/repo/migrations/20250821211457_remove_last_login_timex_column.exs
test/teiserver/account/relationship_lib_test.exs

Fixes #543
Fixing `last_login` field always being null in DB,  also unravelling some duplication of data.
Originally we had:
DB (ie. `user.last_login`):
`last_login` :datetime  - always null
`last_login_timex` :datetime - set correctly
Cache (ie. `user.data['last_login']`:
`last_login` - unix timestamp
`last_login_timex` - datetime
`last_login_mins` - unix timestamp (same value as `last_login`)
In the new state, `last_login` populates correctly, and the data duplication is reduced
DB:
`last_login` :datettime - correctly populates
~~last_login_timex~~ - removed from all code references and replaced with `last_login`, and there is a database migration to purge it
Cache:
`last_login` - datettime
~~last_login_timex~~ removed, references updated to `last_login`
`last_login_mins` - untouched …

Fix last_login db field being null

---

lib/teiserver/party.ex
lib/teiserver/party/server.ex
lib/teiserver/party/supervisor.ex
lib/teiserver/player.ex
test/teiserver_web/tachyon/party_test.exs

Small refactoring before fixing a bug: the party process would never exit if the last remaining member did not cleanly leave and instead disconnected.

Kill party on disconnect

---

lib/teiserver/bridge/discord_bridge_bot.ex

- Fixed Null Comparision error for `new_report` happens if a report comes in without specifying a match
- Fixed oversight of editing a message on `updated_report` even tho no changes were made but still attempting to edit (consuming 1 edit request uselessly)

Fixed hidden bug with latest bridge

---

lib/teiserver/account/schemas/user.ex

Group definitions by arity, otherwise we get:
```
Compiling 741 files (.ex)
warning: clauses with the same name should be grouped together, "def changeset/3" was previously defined (lib/teiserver/account/schemas/user.ex:92)
│
159 │   def changeset(struct, params, nil), do: changeset(struct, params)
│       ~
│
└─ lib/teiserver/account/schemas/user.ex:159:7
warning: clauses with the same name should be grouped together, "def changeset/4" was previously defined (lib/teiserver/account/schemas/user.ex:114)
│
259 │   def changeset(user, attrs, :register, password_type) do
│       ~
│
└─ lib/teiserver/account/schemas/user.ex:259:7
```

Fix compiler warning

---

lib/teiserver/bridge/discord_bridge_bot.ex

This changes the link on reports to no longer link to the admin pages, but instead to the pages accessible to overwatch members

Link to overwatch profiles, not admin profiles

---

lib/teiserver_web/controllers/telemetry/infolog_controller.ex
mix.exs

from the doc:
• --warnings-as-errors - exit with non-zero status if compilation has one
or more warnings. Only concerns compilation warnings from the project, not
its dependencies.

Fix unused imports for good

---

lib/teiserver/moderation/libs/ban_lib.ex
lib/teiserver/moderation/libs/report_lib.ex

Trying to order reports or bans by name (Order by Name A-Z etc.) caused a 500 internal server error.

FIX ordering by name in reports and bans

---

mix.exs

Now that we have fatal compiler warnings, this causes the production
build to fail when some dependencies are not available in the prod env.
For example, HTTPoison used in one task.
Since mix isn't available on the prod servers, we can disable the
compilation of theses tasks.

Exclude mix tasks from compilation in prod env

---

test/teiserver_web/tachyon/lobby_test.exs

Failed when merged 2 different branches where one change would make the test in the other branch fail.

Fix failing test

---

lib/teiserver/player/session.ex
lib/teiserver/player/tachyon_handler.ex
lib/teiserver/tachyon_lobby/list.ex
lib/teiserver/tachyon_lobby/lobby.ex
lib/teiserver/tachyon_lobby/registry.ex
test/teiserver/tachyon_lobby/list_test.exs
test/teiserver_web/tachyon/lobby_test.exs

Because there is a single process responsible for the listing of lobbies, if this process crash and restart, the listing may become desync with what the clients have.
This address this issue by bootstrapping the state of the listing at startup.

Restore lobby list at startup

---

lib/teiserver_web/live/components/player_list_component.ex

Closes #778
Fixed PlayerListComponent.update_many/1 to properly handle {assigns, socket} tuple format

Fix live chat internal server error

---

lib/teiserver/player/session.ex
lib/teiserver/tachyon_lobby/lobby.ex
test/teiserver_web/tachyon/session_test.exs

This fixes a bug where, if the player disconnects abruptly, and then
reconnects, the session wouldn't monitor the new connection process.
So when that new connection disappear abruptly as well, the session
would linger.
Also added a few logs related to lobbies.

Resetup connection monitor

---

assets/scss/mdb/_navbar.scss
lib/teiserver_web/components/nav_components.ex
lib/teiserver_web/components/user_components.ex
lib/teiserver_web/templates/general/general/unauth_index.html.heex
priv/static/images/logo/logo.svg

FIxing the navbar to be properly responsive for small display sizes
- Added responsiveness to navbar, when collapsed the menu is accessible through the hamburger icon
- Added the BAR logo.svg (stolen from bar-lobby) to replace the robot and the BAR text
- Renamed `My account` and `Account` to `Profile` to reflect the actual url route and avoid 'my account' collapsing weirdly to two lines
Uncollapsed:
Collapsed:
Note:  I made a css change so a `mix assets.deploy` will need to be run to recompile this so the dropdown menus properly expand in the collapsed nav.

Responsive Navbar & BAR logo
